import { LibraryResource } from '../types';

export const projectResources: LibraryResource[] = [
  // ==================== BEGINNER PROJECTS ====================
  {
    id: 'proj-beg-1',
    curriculumKey: 'PROJ_BEGINNER',
    language: 'All',
    title: 'Interactive Task Planner & Kanban Workspace (React / Vanilla JS)',
    provider: 'FreeCodeCamp',
    type: 'project',
    level: 'beginner',
    estimatedHours: 15,
    tags: ['Project', 'Frontend', 'React', 'Local Storage', 'State Management'],
    url: 'https://www.freecodecamp.org/news/build-a-todo-app-with-react/',
    free: true,
    order: 1,
    stage: 'project',
  },
  {
    id: 'proj-beg-2',
    curriculumKey: 'PROJ_BEGINNER',
    language: 'All',
    title: 'Weather & Climate Dashboard (REST API Fetching & Dynamic UI)',
    provider: 'FreeCodeCamp',
    type: 'project',
    level: 'beginner',
    estimatedHours: 12,
    tags: ['Project', 'Frontend', 'Async JS', 'OpenWeather API'],
    url: 'https://www.freecodecamp.org/news/learn-javascript-by-building-a-weather-app/',
    free: true,
    order: 2,
    stage: 'project',
  },
  {
    id: 'proj-beg-3',
    curriculumKey: 'PROJ_BEGINNER',
    language: 'All',
    title: 'Personal Developer Portfolio Website with Responsive CSS Grid & Animations',
    provider: 'FreeCodeCamp',
    type: 'project',
    level: 'beginner',
    estimatedHours: 10,
    tags: ['Project', 'HTML', 'CSS', 'Portfolio', 'Vercel'],
    url: 'https://www.freecodecamp.org/news/how-to-build-a-portfolio-website/',
    free: true,
    order: 3,
    stage: 'project',
  },

  // ==================== INTERMEDIATE PROJECTS ====================
  {
    id: 'proj-int-1',
    curriculumKey: 'PROJ_INTERMEDIATE',
    language: 'All',
    title: 'Full-Stack MERN E-Commerce Platform with Auth, Cart & Payment Simulation',
    provider: 'FreeCodeCamp',
    type: 'project',
    level: 'intermediate',
    estimatedHours: 30,
    tags: ['Project', 'Full-Stack', 'Node.js', 'Express', 'MongoDB', 'JWT', 'React'],
    url: 'https://www.freecodecamp.org/news/create-a-fullstack-mern-app-from-scratch/',
    free: true,
    order: 1,
    stage: 'project',
  },
  {
    id: 'proj-int-2',
    curriculumKey: 'PROJ_INTERMEDIATE',
    language: 'All',
    title: 'Collaborative Real-Time Chat & Messaging Engine (Node.js & Socket.io)',
    provider: 'FreeCodeCamp',
    type: 'project',
    level: 'intermediate',
    estimatedHours: 25,
    tags: ['Project', 'Node.js', 'Socket.io', 'WebSockets', 'Render'],
    url: 'https://www.freecodecamp.org/news/build-a-realtime-chat-app-with-react-node-socketio/',
    free: true,
    order: 2,
    stage: 'project',
  },
  {
    id: 'proj-int-3',
    curriculumKey: 'PROJ_INTERMEDIATE',
    language: 'All',
    title: 'RESTful Blog & Content Management Engine with Role-Based Access Control',
    provider: 'GeeksforGeeks',
    type: 'project',
    level: 'intermediate',
    estimatedHours: 20,
    tags: ['Project', 'Backend', 'Express', 'SQL', 'PostgreSQL', 'RBAC'],
    url: 'https://www.geeksforgeeks.org/nodejs-blog-application/',
    free: true,
    order: 3,
    stage: 'project',
  },

  // ==================== ADVANCED CAPSTONE PROJECTS ====================
  {
    id: 'proj-adv-1',
    curriculumKey: 'PROJ_ADVANCED',
    language: 'All',
    title: 'Scalable Distributed URL Shortener & Analytics System (System Design & Redis Caching)',
    provider: 'System Design Primer',
    type: 'project',
    level: 'advanced',
    estimatedHours: 40,
    tags: ['Project', 'System Design', 'Redis', 'Docker', 'PostgreSQL', 'Microservices'],
    url: 'https://github.com/donnemartin/system-design-primer#url-shortener',
    free: true,
    order: 1,
    stage: 'project',
  },
  {
    id: 'proj-adv-2',
    curriculumKey: 'PROJ_ADVANCED',
    language: 'All',
    title: 'Real-Time Scalable Video Streaming or AI Career Engine Platform (Docker & AWS Deployment)',
    provider: 'FreeCodeCamp',
    type: 'project',
    level: 'advanced',
    estimatedHours: 50,
    tags: ['Project', 'Docker', 'AWS', 'Next.js', 'TailwindCSS', 'TypeScript'],
    url: 'https://www.freecodecamp.org/news/build-and-deploy-a-full-stack-web3-or-microservice-app/',
    free: true,
    order: 2,
    stage: 'project',
  },
];
