import { LibraryResource } from '../types';

export const csCoreResources: LibraryResource[] = [
  // ==================== OOP ====================
  {
    id: 'cs-oop-learn-1',
    curriculumKey: 'CS_OOP',
    language: 'All',
    title: 'GeeksforGeeks: Object-Oriented Programming Principles (Abstraction, Encapsulation, Inheritance, Polymorphism)',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 6,
    tags: ['OOP', 'Inheritance', 'Polymorphism', 'Encapsulation'],
    url: 'https://www.geeksforgeeks.org/object-oriented-programming-in-cpp/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'cs-oop-learn-2',
    curriculumKey: 'CS_OOP',
    language: 'Java',
    title: 'Kunal Kushwaha: Java OOPs Concept, Classes, Objects & Inheritance',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['OOP', 'Java', 'Classes'],
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7gFc1UMAxqv6t5P',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'cs-oop-notes-1',
    curriculumKey: 'CS_OOP',
    language: 'All',
    title: 'Refactoring Guru: SOLID Principles & Design Patterns Complete Guide',
    provider: 'Refactoring Guru',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['OOP', 'SOLID', 'Design Patterns'],
    url: 'https://refactoring.guru/solid-principles',
    free: true,
    order: 3,
    stage: 'notes',
  },
  {
    id: 'cs-oop-notes-2',
    curriculumKey: 'CS_OOP',
    language: 'All',
    title: 'Refactoring Guru: Creational, Structural & Behavioral Design Patterns in Java/C++',
    provider: 'Refactoring Guru',
    type: 'article',
    level: 'advanced',
    estimatedHours: 10,
    tags: ['OOP', 'Design Patterns', 'Factory', 'Observer'],
    url: 'https://refactoring.guru/design-patterns/catalog',
    free: true,
    order: 4,
    stage: 'notes',
  },
  {
    id: 'cs-oop-interview-1',
    curriculumKey: 'CS_OOP',
    language: 'All',
    title: 'Top OOP Interview Questions & Real-World Code Examples',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['OOP', 'Interview', 'SOLID Principles'],
    url: 'https://www.geeksforgeeks.org/oops-interview-questions/',
    free: true,
    order: 5,
    stage: 'interview',
  },

  // ==================== OPERATING SYSTEMS ====================
  {
    id: 'cs-os-learn-1',
    curriculumKey: 'CS_OS',
    language: 'All',
    title: 'Gate Smashers: Operating Systems (OS) Complete Playlist',
    provider: 'Gate Smashers',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 15,
    tags: ['OS', 'Processes', 'Threads', 'Deadlocks', 'Virtual Memory'],
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'cs-os-learn-2',
    curriculumKey: 'CS_OS',
    language: 'All',
    title: 'NPTEL: Operating System Fundamentals Course Lectures by IIT Kharagpur',
    provider: 'NPTEL IIT',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 15,
    tags: ['OS', 'NPTEL', 'IIT'],
    url: 'https://nptel.ac.in/courses/106105214',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'cs-os-notes-1',
    curriculumKey: 'CS_OS',
    language: 'All',
    title: 'GeeksforGeeks: Operating System Revision Notes & CPU Scheduling Algorithms',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['OS', 'Notes', 'CPU Scheduling'],
    url: 'https://www.geeksforgeeks.org/operating-systems/',
    free: true,
    order: 3,
    stage: 'notes',
  },
  {
    id: 'cs-os-notes-2',
    curriculumKey: 'CS_OS',
    language: 'All',
    title: 'Operating System Concepts (Silberschatz) Free Lecture Notes & Slides',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['OS', 'Silberschatz', 'Slides'],
    url: 'https://www.os-book.com/OS10/slide-dir/index.html',
    free: true,
    order: 4,
    stage: 'notes',
  },
  {
    id: 'cs-os-interview-1',
    curriculumKey: 'CS_OS',
    language: 'All',
    title: 'Top OS Interview Questions for Software Engineers (Process vs Thread, Mutex vs Semaphore)',
    provider: 'TakeUForward',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['OS', 'Interview', 'Deadlocks'],
    url: 'https://takeuforward.org/operating-system/operating-system-interview-questions/',
    free: true,
    order: 5,
    stage: 'interview',
  },

  // ==================== DBMS ====================
  {
    id: 'cs-dbms-learn-1',
    curriculumKey: 'CS_DBMS',
    language: 'All',
    title: 'Gate Smashers: DBMS Complete Playlist (Normalization, ACID Properties, Transactions, Indexing)',
    provider: 'Gate Smashers',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 16,
    tags: ['DBMS', 'ACID', 'Normalization', 'Indexing', 'Transactions'],
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGGWpErHsJeU15Lfy1dFXX_',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'cs-dbms-learn-2',
    curriculumKey: 'CS_DBMS',
    language: 'All',
    title: 'CMU Database Group: Introduction to Database Systems Lectures by Andy Pavlo',
    provider: 'CMU University',
    type: 'video',
    level: 'advanced',
    estimatedHours: 18,
    tags: ['DBMS', 'CMU', 'B+ Trees', 'Buffer Pool'],
    url: 'https://15445.courses.cs.cmu.edu/',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'cs-dbms-notes-1',
    curriculumKey: 'CS_DBMS',
    language: 'All',
    title: 'GeeksforGeeks: DBMS Complete Tutorials & Revision Notes',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['DBMS', 'Notes', 'ER Diagrams'],
    url: 'https://www.geeksforgeeks.org/dbms/',
    free: true,
    order: 3,
    stage: 'notes',
  },
  {
    id: 'cs-dbms-interview-1',
    curriculumKey: 'CS_DBMS',
    language: 'All',
    title: 'Top 50 DBMS Interview Questions & Answers',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['DBMS', 'Interview', 'ACID'],
    url: 'https://www.geeksforgeeks.org/dbms-interview-questions/',
    free: true,
    order: 4,
    stage: 'interview',
  },

  // ==================== COMPUTER NETWORKS ====================
  {
    id: 'cs-cn-learn-1',
    curriculumKey: 'CS_CN',
    language: 'All',
    title: 'Gate Smashers: Computer Networks (CN) Complete Playlist (OSI Model, TCP/IP, DNS, HTTP)',
    provider: 'Gate Smashers',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 15,
    tags: ['CN', 'OSI Model', 'TCP/IP', 'HTTP', 'DNS'],
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLgD2aNp2B',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'cs-cn-notes-1',
    curriculumKey: 'CS_CN',
    language: 'All',
    title: 'Computer Networking: A Top-Down Approach Online Lectures by Kurose & Ross',
    provider: 'Official Docs',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 10,
    tags: ['CN', 'Kurose Ross', 'Protocols'],
    url: 'https://gaia.cs.umass.edu/kurose_ross/online_lectures.htm',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'cs-cn-interview-1',
    curriculumKey: 'CS_CN',
    language: 'All',
    title: 'Top Computer Networks Interview Questions (TCP Handshake, IP Addressing, Subnetting)',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['CN', 'Interview', 'TCP'],
    url: 'https://www.geeksforgeeks.org/computer-network-interview-questions/',
    free: true,
    order: 3,
    stage: 'interview',
  },

  // ==================== SYSTEM DESIGN (HLD & LLD) ====================
  {
    id: 'cs-sd-learn-1',
    curriculumKey: 'CS_SYSTEM_DESIGN',
    language: 'All',
    title: 'System Design Primer by Donne Martin (GitHub Repository)',
    provider: 'System Design Primer',
    type: 'article',
    level: 'advanced',
    estimatedHours: 20,
    tags: ['System Design', 'HLD', 'Scalability', 'Load Balancing'],
    url: 'https://github.com/donnemartin/system-design-primer',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'cs-sd-learn-2',
    curriculumKey: 'CS_SYSTEM_DESIGN',
    language: 'All',
    title: 'Gaurav Sen: System Design (HLD & LLD) Complete Playlist',
    provider: 'Gaurav Sen',
    type: 'video',
    level: 'advanced',
    estimatedHours: 15,
    tags: ['System Design', 'Gaurav Sen', 'Microservices'],
    url: 'https://www.youtube.com/playlist?list=PLMCXHnjXnJeMhsRx1hF9mGZ7bjd50A1r7',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'cs-sd-learn-3',
    curriculumKey: 'CS_SYSTEM_DESIGN',
    language: 'All',
    title: 'ByteByteGo: System Design Interview Concepts (Rate Limiting, Consistent Hashing)',
    provider: 'ByteByteGo',
    type: 'article',
    level: 'advanced',
    estimatedHours: 10,
    tags: ['System Design', 'ByteByteGo', 'Hashing'],
    url: 'https://bytebytego.com',
    free: true,
    order: 3,
    stage: 'learn',
  },
  {
    id: 'cs-lld-learn-1',
    curriculumKey: 'CS_LLD',
    language: 'All',
    title: 'Low Level Design (LLD) & Object-Oriented Design Interview Questions',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 10,
    tags: ['LLD', 'System Design', 'OOD', 'Design Patterns'],
    url: 'https://www.geeksforgeeks.org/system-design-lld-low-level-design/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'cs-lld-learn-2',
    curriculumKey: 'CS_LLD',
    language: 'All',
    title: 'Concept & Coding by Shrayansh: Low Level Design (LLD) Problems (TicTacToe, Elevator, Parking Lot)',
    provider: 'Concept Coding',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 12,
    tags: ['LLD', 'Parking Lot', 'Elevator', 'OOD'],
    url: 'https://www.youtube.com/playlist?list=PL6W8uoQQ2c61X_wjtynPgWYXOfVfacC68',
    free: true,
    order: 2,
    stage: 'learn',
  },
];
