import { LibraryResource } from '../types';

export const aptitudeResources: LibraryResource[] = [
  // ==================== QUANTITATIVE APTITUDE ====================
  {
    id: 'apt-quant-learn-1',
    curriculumKey: 'APT_QUANT',
    language: 'All',
    title: 'IndiaBix: Quantitative Aptitude Solved Questions, Formulas & Practice Tests',
    provider: 'IndiaBix',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 12,
    tags: ['Aptitude', 'Quant', 'Time & Work', 'Percentages', 'Profit & Loss'],
    url: 'https://www.indiabix.com/quantitative-aptitude/questions-and-answers/',
    free: true,
    order: 1,
    stage: 'practice',
  },
  {
    id: 'apt-quant-learn-2',
    curriculumKey: 'APT_QUANT',
    language: 'All',
    title: 'PrepInsta: Quantitative Aptitude Preparation for Campus Placements',
    provider: 'PrepInsta',
    type: 'article',
    level: 'beginner',
    estimatedHours: 10,
    tags: ['Aptitude', 'PrepInsta', 'Placements'],
    url: 'https://prepinsta.com/quantitative-aptitude/',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'apt-quant-learn-3',
    curriculumKey: 'APT_QUANT',
    language: 'All',
    title: 'GeeksforGeeks: Quantitative Aptitude Topics & Solved Examples',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['Aptitude', 'Quant', 'Shortcuts'],
    url: 'https://www.geeksforgeeks.org/aptitude-questions-and-answers/',
    free: true,
    order: 3,
    stage: 'notes',
  },
  {
    id: 'apt-quant-practice-4',
    curriculumKey: 'APT_QUANT',
    language: 'All',
    title: 'IndiaBix: Speed Math, Permutation & Combination Practice Sets',
    provider: 'IndiaBix',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Aptitude', 'Quant', 'Permutation'],
    url: 'https://www.indiabix.com/aptitude/questions-and-answers/',
    free: true,
    order: 4,
    stage: 'practice',
  },
  {
    id: 'apt-quant-practice-5',
    curriculumKey: 'APT_QUANT',
    language: 'All',
    title: 'PrepInsta: Speed, Distance & Time Formulas & Placement Mock Questions',
    provider: 'PrepInsta',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Aptitude', 'Speed Time Distance'],
    url: 'https://prepinsta.com/quantitative-aptitude/speed-distance-time/',
    free: true,
    order: 5,
    stage: 'practice',
  },

  // ==================== LOGICAL REASONING ====================
  {
    id: 'apt-log-learn-1',
    curriculumKey: 'APT_LOGICAL',
    language: 'All',
    title: 'IndiaBix: Logical Reasoning Questions, Puzzles & Practice Exercises',
    provider: 'IndiaBix',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 10,
    tags: ['Aptitude', 'Logical Reasoning', 'Puzzles', 'Blood Relations'],
    url: 'https://www.indiabix.com/logical-reasoning/questions-and-answers/',
    free: true,
    order: 1,
    stage: 'practice',
  },
  {
    id: 'apt-log-learn-2',
    curriculumKey: 'APT_LOGICAL',
    language: 'All',
    title: 'GeeksforGeeks: Logical Reasoning Puzzles & Placement Test Sets',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Aptitude', 'GeeksforGeeks', 'Puzzles'],
    url: 'https://www.geeksforgeeks.org/puzzles/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'apt-log-learn-3',
    curriculumKey: 'APT_LOGICAL',
    language: 'All',
    title: 'PrepInsta: Logical Reasoning Campus Placement Questions',
    provider: 'PrepInsta',
    type: 'article',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['Aptitude', 'PrepInsta', 'Logical'],
    url: 'https://prepinsta.com/logical-reasoning/',
    free: true,
    order: 3,
    stage: 'learn',
  },
  {
    id: 'apt-log-practice-4',
    curriculumKey: 'APT_LOGICAL',
    language: 'All',
    title: 'IndiaBix: Data Interpretation & Chart Analysis Practice',
    provider: 'IndiaBix',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Aptitude', 'Data Interpretation', 'Charts'],
    url: 'https://www.indiabix.com/data-interpretation/questions-and-answers/',
    free: true,
    order: 4,
    stage: 'practice',
  },

  // ==================== VERBAL ABILITY ====================
  {
    id: 'apt-verb-learn-1',
    curriculumKey: 'APT_VERBAL',
    language: 'All',
    title: 'IndiaBix: Verbal Ability Grammar, Reading Comprehension & Vocabulary Exercises',
    provider: 'IndiaBix',
    type: 'practice',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['Aptitude', 'Verbal Ability', 'English', 'Grammar'],
    url: 'https://www.indiabix.com/verbal-ability/questions-and-answers/',
    free: true,
    order: 1,
    stage: 'practice',
  },
  {
    id: 'apt-verb-learn-2',
    curriculumKey: 'APT_VERBAL',
    language: 'All',
    title: 'PrepInsta: Verbal Ability English Questions & Practice Sets for Campus Placements',
    provider: 'PrepInsta',
    type: 'article',
    level: 'beginner',
    estimatedHours: 6,
    tags: ['Aptitude', 'Verbal', 'PrepInsta'],
    url: 'https://prepinsta.com/verbal-ability/',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'apt-verb-notes-3',
    curriculumKey: 'APT_VERBAL',
    language: 'All',
    title: 'GeeksforGeeks: Verbal Ability English Grammar Rules & Error Spotting Guide',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 5,
    tags: ['Aptitude', 'Verbal', 'Grammar Rules'],
    url: 'https://www.geeksforgeeks.org/english-grammar/',
    free: true,
    order: 3,
    stage: 'notes',
  },
];
