import { LibraryResource } from '../types';

export const dsaArraysResources: LibraryResource[] = [
  // ==================== JAVA ====================
  {
    id: 'dsa-arr-java-learn',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Java',
    title: 'Kunal Kushwaha: Arrays & ArrayList Data Structure in Java',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Arrays', 'Java', 'ArrayList', 'Memory Allocation'],
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7gFc1UMAxqv6t5P',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-arr-java-notes',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Java',
    title: 'Striver A2Z Java DSA Sheet: Array Fundamentals & Memory Layout',
    provider: 'TakeUForward',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Arrays', 'Java', 'Notes', 'Pass-by-value'],
    url: 'https://takeuforward.org/data-structure/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-arr-java-practice',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Java',
    title: 'LeetCode Explore: Arrays 101 & Top 15 Array Problems (Java)',
    provider: 'LeetCode',
    type: 'practice',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['Arrays', 'LeetCode', 'Practice'],
    url: 'https://leetcode.com/explore/learn/card/fun-with-arrays/',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-arr-java-interview',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Java',
    title: 'Top Array Interview Questions (Two Sum, Kadane Algorithm, 3Sum in Java)',
    provider: 'TakeUForward',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Arrays', 'Interview', 'Kadane', 'Two Sum'],
    url: 'https://takeuforward.org/interviews/top-array-interview-questions-structured-path/',
    free: true,
    order: 4,
    stage: 'interview',
  },
  {
    id: 'dsa-arr-java-interview-2',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Java',
    title: 'GeeksforGeeks: Majority Element (Boyer-Moore Voting Algorithm in Java)',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 3,
    tags: ['Arrays', 'Java', 'Boyer-Moore'],
    url: 'https://www.geeksforgeeks.org/boyer-moore-majority-voting-algorithm/',
    free: true,
    order: 5,
    stage: 'interview',
  },
  {
    id: 'dsa-arr-java-revision',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Java',
    title: 'GeeksforGeeks Java Array Operations & Time Complexity Cheat Sheet',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Arrays', 'Java', 'Revision'],
    url: 'https://www.geeksforgeeks.org/array-data-structure/',
    free: true,
    order: 6,
    stage: 'revision',
  },

  // ==================== PYTHON ====================
  {
    id: 'dsa-arr-py-learn',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Python',
    title: 'NeetCode Python: Static Arrays, Dynamic Arrays & Lists',
    provider: 'NeetCode',
    type: 'video',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Arrays', 'Python', 'Lists', 'Dynamic Arrays'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/1',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-arr-py-notes',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Python',
    title: 'GeeksforGeeks: Python Arrays & List Internal Architecture',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Arrays', 'Python', 'Memory'],
    url: 'https://www.geeksforgeeks.org/python-arrays/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-arr-py-practice',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Python',
    title: 'NeetCode 150: Array & Hashing Python Practice Sheet',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Arrays', 'Python', 'LeetCode'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-arr-py-interview',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Python',
    title: 'Top Python Array Coding Interview Problems with Explanations',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Arrays', 'Python', 'Interview'],
    url: 'https://www.geeksforgeeks.org/top-50-array-coding-problems-for-interviews/',
    free: true,
    order: 4,
    stage: 'interview',
  },
  {
    id: 'dsa-arr-py-interview-2',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Python',
    title: 'Real Python: Maximum Subarray Sum & Prefix Sum Pattern in Python',
    provider: 'Real Python',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 3,
    tags: ['Arrays', 'Python', 'Prefix Sum'],
    url: 'https://realpython.com/python-lists-tuples/#list-indexing-and-slicing',
    free: true,
    order: 5,
    stage: 'interview',
  },
  {
    id: 'dsa-arr-py-revision',
    curriculumKey: 'DSA_ARRAYS',
    language: 'Python',
    title: 'Python List Slicing & Array Manipulations Revision Notes',
    provider: 'Real Python',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Arrays', 'Python', 'Revision'],
    url: 'https://realpython.com/python-lists-tuples/',
    free: true,
    order: 6,
    stage: 'revision',
  },

  // ==================== C++ ====================
  {
    id: 'dsa-arr-cpp-learn',
    curriculumKey: 'DSA_ARRAYS',
    language: 'C++',
    title: 'Striver C++ DSA Bootcamp: Arrays & Vectors Complete Guide',
    provider: 'Striver',
    type: 'video',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Arrays', 'C++', 'Vectors', 'Pointers'],
    url: 'https://youtu.be/37E9ckMDdTk',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-arr-cpp-notes',
    curriculumKey: 'DSA_ARRAYS',
    language: 'C++',
    title: 'Abdul Bari: Array Representation, Memory Layout & Operations',
    provider: 'Abdul Bari',
    type: 'video',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Arrays', 'C++', 'Memory', 'Stack vs Heap'],
    url: 'https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-arr-cpp-practice',
    curriculumKey: 'DSA_ARRAYS',
    language: 'C++',
    title: 'Striver A2Z C++ Sheet: Array Easy, Medium, Hard Problems',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 10,
    tags: ['Arrays', 'C++', 'Practice', 'LeetCode'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-arr-cpp-interview',
    curriculumKey: 'DSA_ARRAYS',
    language: 'C++',
    title: 'Top Array Interview Questions in C++ (Dutch National Flag, Subarray Sum)',
    provider: 'TakeUForward',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Arrays', 'C++', 'Interview'],
    url: 'https://takeuforward.org/array/dutch-national-flag-algorithm/',
    free: true,
    order: 4,
    stage: 'interview',
  },
  {
    id: 'dsa-arr-cpp-interview-2',
    curriculumKey: 'DSA_ARRAYS',
    language: 'C++',
    title: 'GeeksforGeeks C++ Rotate Matrix / 2D Array Traversals',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 3,
    tags: ['Arrays', 'C++', '2D Array'],
    url: 'https://www.geeksforgeeks.org/rotate-a-matrix-by-90-degree-in-clockwise-direction-without-using-any-extra-space/',
    free: true,
    order: 5,
    stage: 'interview',
  },
  {
    id: 'dsa-arr-cpp-revision',
    curriculumKey: 'DSA_ARRAYS',
    language: 'C++',
    title: 'C++ std::vector & Raw Array Memory Revision Cheat Sheet',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Arrays', 'C++', 'Revision'],
    url: 'https://www.geeksforgeeks.org/vector-in-cpp-stl/',
    free: true,
    order: 6,
    stage: 'revision',
  },
];
