import { LibraryResource } from '../types';

export const dsaBitManipulationResources: LibraryResource[] = [
  // ==================== BIT MANIPULATION ====================
  // Java
  {
    id: 'dsa-bit-java-learn',
    curriculumKey: 'DSA_BIT_MANIPULATION',
    language: 'Java',
    title: 'Kunal Kushwaha: Bitwise Operators & Number Systems in Java',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Bit Manipulation', 'Java', 'XOR'],
    url: 'https://youtu.be/fzip9AfWRGE',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-bit-java-practice',
    curriculumKey: 'DSA_BIT_MANIPULATION',
    language: 'Java',
    title: 'Striver A2Z Java Bit Manipulation Sheet (Single Number, Subsets)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Bit Manipulation', 'Java'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-bit-py-learn',
    curriculumKey: 'DSA_BIT_MANIPULATION',
    language: 'Python',
    title: 'NeetCode Python: Bit Manipulation Tricks & Counting Bits',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Bit Manipulation', 'Python'],
    url: 'https://youtu.be/5RTFGsGXpTE',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-bit-py-practice',
    curriculumKey: 'DSA_BIT_MANIPULATION',
    language: 'Python',
    title: 'NeetCode 150 Bit Manipulation Python Exercises',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Bit Manipulation', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-bit-cpp-learn',
    curriculumKey: 'DSA_BIT_MANIPULATION',
    language: 'C++',
    title: 'Striver: Bit Manipulation Complete Series (C++)',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Bit Manipulation', 'C++'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0rnqnSPc_Wj1FuaQTRA8pKM',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-bit-cpp-practice',
    curriculumKey: 'DSA_BIT_MANIPULATION',
    language: 'C++',
    title: 'Striver A2Z C++ Bit Manipulation Problems',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Bit Manipulation', 'C++'],
    url: 'https://takeuforward.org/bit-manipulation/set-the-rightmost-unset-bit/',
    free: true,
    order: 2,
    stage: 'practice',
  },
];

export const dsaAdvancedResources: LibraryResource[] = [
  // ==================== SEGMENT TREE ====================
  // All / Java / Python / C++
  {
    id: 'dsa-segtree-all-learn',
    curriculumKey: 'DSA_SEGMENT_TREE',
    language: 'All',
    title: 'CP-Algorithms: Segment Tree Complete Range Query Guide',
    provider: 'CP-Algorithms',
    type: 'article',
    level: 'advanced',
    estimatedHours: 8,
    tags: ['Segment Tree', 'Range Queries', 'Advanced DSA'],
    url: 'https://cp-algorithms.com/data_structures/segment_tree.html',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-segtree-java-learn',
    curriculumKey: 'DSA_SEGMENT_TREE',
    language: 'Java',
    title: 'Striver: Segment Tree Series (Java Building, Point Update, Range Query)',
    provider: 'TakeUForward',
    type: 'video',
    level: 'advanced',
    estimatedHours: 6,
    tags: ['Segment Tree', 'Java'],
    url: 'https://takeuforward.org/segment-tree/segment-tree-intro-building-point-update-range-sum-query/',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'dsa-segtree-py-learn',
    curriculumKey: 'DSA_SEGMENT_TREE',
    language: 'Python',
    title: 'NeetCode Python: Segment Tree Implementation & Range Queries',
    provider: 'NeetCode',
    type: 'video',
    level: 'advanced',
    estimatedHours: 5,
    tags: ['Segment Tree', 'Python'],
    url: 'https://neetcode.io/courses/advanced-algorithms/2',
    free: true,
    order: 3,
    stage: 'learn',
  },
  {
    id: 'dsa-segtree-cpp-learn',
    curriculumKey: 'DSA_SEGMENT_TREE',
    language: 'C++',
    title: 'Striver: Segment Tree Lazy Propagation in C++',
    provider: 'Striver',
    type: 'video',
    level: 'advanced',
    estimatedHours: 6,
    tags: ['Segment Tree', 'C++'],
    url: 'https://takeuforward.org/segment-tree/lazy-propagation-segment-tree-tutorial/',
    free: true,
    order: 4,
    stage: 'learn',
  },

  // ==================== DSU ====================
  // All / Java / Python / C++
  {
    id: 'dsa-dsu-all-learn',
    curriculumKey: 'DSA_DSU',
    language: 'All',
    title: 'CP-Algorithms: Disjoint Set Union (DSU / Union-Find)',
    provider: 'CP-Algorithms',
    type: 'article',
    level: 'advanced',
    estimatedHours: 6,
    tags: ['DSU', 'Union-Find', 'Graphs'],
    url: 'https://cp-algorithms.com/data_structures/disjoint_set_union.html',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-dsu-java-learn',
    curriculumKey: 'DSA_DSU',
    language: 'Java',
    title: 'Striver: Disjoint Set Union (Java Union by Rank & Path Compression)',
    provider: 'TakeUForward',
    type: 'video',
    level: 'advanced',
    estimatedHours: 5,
    tags: ['DSU', 'Java'],
    url: 'https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'dsa-dsu-py-learn',
    curriculumKey: 'DSA_DSU',
    language: 'Python',
    title: 'NeetCode Python: Union-Find (Disjoint Set) Algorithm & Graph Problems',
    provider: 'NeetCode',
    type: 'video',
    level: 'advanced',
    estimatedHours: 5,
    tags: ['DSU', 'Python'],
    url: 'https://neetcode.io/courses/advanced-algorithms/1',
    free: true,
    order: 3,
    stage: 'learn',
  },
  {
    id: 'dsa-dsu-cpp-learn',
    curriculumKey: 'DSA_DSU',
    language: 'C++',
    title: 'Striver: Disjoint Set [Union by Rank/Size] & Kruskal Algorithm in C++',
    provider: 'Striver',
    type: 'video',
    level: 'advanced',
    estimatedHours: 5,
    tags: ['DSU', 'C++', 'Kruskal'],
    url: 'https://youtu.be/aBxjGSiL34M',
    free: true,
    order: 4,
    stage: 'learn',
  },
];
