import { LibraryResource } from '../types';

export const dsaGraphsResources: LibraryResource[] = [
  // Java
  {
    id: 'dsa-graph-java-learn',
    curriculumKey: 'DSA_GRAPHS',
    language: 'Java',
    title: 'Striver: Graph Series Playlist (Java BFS, DFS, Dijkstra, Bellman-Ford)',
    provider: 'TakeUForward',
    type: 'video',
    level: 'advanced',
    estimatedHours: 18,
    tags: ['Graphs', 'Java', 'BFS', 'DFS', 'Dijkstra'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0oE3g1t1gT0GsDYmF0gMC9g',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-graph-java-practice',
    curriculumKey: 'DSA_GRAPHS',
    language: 'Java',
    title: 'Striver A2Z Java Graph Sheet: Topological Sort, Cycle Detection, MST',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 12,
    tags: ['Graphs', 'Java'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-graph-py-learn',
    curriculumKey: 'DSA_GRAPHS',
    language: 'Python',
    title: 'NeetCode Python: Graphs DFS & BFS Algorithms & LeetCode Hard Problems',
    provider: 'NeetCode',
    type: 'video',
    level: 'advanced',
    estimatedHours: 12,
    tags: ['Graphs', 'Python', 'Adjacency List'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/26',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-graph-py-practice',
    curriculumKey: 'DSA_GRAPHS',
    language: 'Python',
    title: 'NeetCode 150 Graph Python Category Solutions',
    provider: 'NeetCode',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 10,
    tags: ['Graphs', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-graph-cpp-learn',
    curriculumKey: 'DSA_GRAPHS',
    language: 'C++',
    title: 'Striver: Graph Series Playlist in C++ (Topological Sort, MST, Disjoint Set)',
    provider: 'Striver',
    type: 'video',
    level: 'advanced',
    estimatedHours: 18,
    tags: ['Graphs', 'C++', 'Kruskal', 'Prim'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0oE3g1t1gT0GsDYmF0gMC9g',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-graph-cpp-practice',
    curriculumKey: 'DSA_GRAPHS',
    language: 'C++',
    title: 'Striver A2Z C++ Graph Sheet: Shortest Path Algorithms & Tarjan Bridges',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 12,
    tags: ['Graphs', 'C++', 'Dijkstra', 'Tarjan'],
    url: 'https://takeuforward.org/graph/dijkstras-algorithm-using-set-g-33/',
    free: true,
    order: 2,
    stage: 'practice',
  },
];

export const dsaDpResources: LibraryResource[] = [
  // Java
  {
    id: 'dsa-dp-java-learn',
    curriculumKey: 'DSA_DP',
    language: 'Java',
    title: 'Striver: Dynamic Programming Series (Java Memoization & Tabulation)',
    provider: 'TakeUForward',
    type: 'video',
    level: 'advanced',
    estimatedHours: 20,
    tags: ['DP', 'Java', '1D DP', '2D DP', 'Subsets'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0qUlt5y6ysfCcnPxTP_GFLu',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-dp-java-practice',
    curriculumKey: 'DSA_DP',
    language: 'Java',
    title: 'Striver A2Z Java DP Sheet: 1D/2D DP, Subsets, Strings, Stocks & Trees',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 15,
    tags: ['DP', 'Java'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-dp-py-learn',
    curriculumKey: 'DSA_DP',
    language: 'Python',
    title: 'FreeCodeCamp: Dynamic Programming Tutorial (Python Memoization & Tabulation)',
    provider: 'FreeCodeCamp',
    type: 'video',
    level: 'advanced',
    estimatedHours: 15,
    tags: ['DP', 'Python', 'Memoization'],
    url: 'https://youtu.be/oBt53YbR9Kk',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-dp-py-practice',
    curriculumKey: 'DSA_DP',
    language: 'Python',
    title: 'NeetCode 150 1D & 2D Dynamic Programming Python Problems',
    provider: 'NeetCode',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 12,
    tags: ['DP', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-dp-cpp-learn',
    curriculumKey: 'DSA_DP',
    language: 'C++',
    title: 'Striver: Dynamic Programming Series in C++ (DP on Trees, DP on Grids, LCS, Knapsack)',
    provider: 'Striver',
    type: 'video',
    level: 'advanced',
    estimatedHours: 20,
    tags: ['DP', 'C++', 'Knapsack', 'LCS'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0qUlt5y6ysfCcnPxTP_GFLu',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-dp-cpp-practice',
    curriculumKey: 'DSA_DP',
    language: 'C++',
    title: 'Striver A2Z C++ DP Sheet: Matrix Chain Multiplication & Partition DP',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 15,
    tags: ['DP', 'C++', 'MCM'],
    url: 'https://takeuforward.org/dynamic-programming/matrix-chain-multiplication-dp-48/',
    free: true,
    order: 2,
    stage: 'practice',
  },
];
