import { LibraryResource } from '../types';

export const dsaGreedyBacktrackingResources: LibraryResource[] = [
  // ==================== GREEDY ====================
  // Java
  {
    id: 'dsa-greedy-java-learn',
    curriculumKey: 'DSA_GREEDY',
    language: 'Java',
    title: 'Striver: Greedy Algorithms Playlist in Java',
    provider: 'TakeUForward',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Greedy', 'Java', 'Intervals'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0pl5q_9n2L8fQ-QkGgq-zGq',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-greedy-java-practice',
    curriculumKey: 'DSA_GREEDY',
    language: 'Java',
    title: 'Striver A2Z Java Greedy Problems (N Meetings in One Room, Job Sequencing)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Greedy', 'Java'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-greedy-py-learn',
    curriculumKey: 'DSA_GREEDY',
    language: 'Python',
    title: 'NeetCode Python: Greedy Algorithms Strategy & LeetCode Problems',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Greedy', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-greedy-py-practice',
    curriculumKey: 'DSA_GREEDY',
    language: 'Python',
    title: 'NeetCode 150 Greedy Category Python Exercises',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Greedy', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-greedy-cpp-learn',
    curriculumKey: 'DSA_GREEDY',
    language: 'C++',
    title: 'Striver: Greedy Algorithms Series in C++',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Greedy', 'C++'],
    url: 'https://youtu.be/F2oVlh584bA',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-greedy-cpp-practice',
    curriculumKey: 'DSA_GREEDY',
    language: 'C++',
    title: 'Striver A2Z C++ Greedy Sheet (Non-Overlapping Intervals, Fractional Knapsack)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Greedy', 'C++'],
    url: 'https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // ==================== BACKTRACKING ====================
  // Java
  {
    id: 'dsa-bt-java-learn',
    curriculumKey: 'DSA_BACKTRACKING',
    language: 'Java',
    title: 'Kunal Kushwaha: Recursion & Backtracking in Java (N-Queens, Sudoku Solver)',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'advanced',
    estimatedHours: 8,
    tags: ['Backtracking', 'Java', 'N-Queens'],
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnpFD6g2t2Wnmj1D6Uj1G2eP',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-rec-java-learn',
    curriculumKey: 'DSA_RECURSION',
    language: 'Java',
    title: 'Kunal Kushwaha: Complete Recursion Course in Java',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['Recursion', 'Java', 'Call Stack'],
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnpFD6g2t2Wnmj1D6Uj1G2eP',
    free: true,
    order: 1,
    stage: 'learn',
  },

  // Python
  {
    id: 'dsa-bt-py-learn',
    curriculumKey: 'DSA_BACKTRACKING',
    language: 'Python',
    title: 'NeetCode Python: Backtracking Algorithms (Subsets, Combinations, Permutations)',
    provider: 'NeetCode',
    type: 'video',
    level: 'advanced',
    estimatedHours: 6,
    tags: ['Backtracking', 'Python'],
    url: 'https://youtu.be/Nn81Ipq-Aqo',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-rec-py-learn',
    curriculumKey: 'DSA_RECURSION',
    language: 'Python',
    title: 'NeetCode Python: Recursion Theory & Call Stack Mechanics',
    provider: 'NeetCode',
    type: 'video',
    level: 'beginner',
    estimatedHours: 5,
    tags: ['Recursion', 'Python'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/11',
    free: true,
    order: 1,
    stage: 'learn',
  },

  // C++
  {
    id: 'dsa-bt-cpp-learn',
    curriculumKey: 'DSA_BACKTRACKING',
    language: 'C++',
    title: 'Abdul Bari: Backtracking Algorithms & State Space Trees',
    provider: 'Abdul Bari',
    type: 'video',
    level: 'advanced',
    estimatedHours: 6,
    tags: ['Backtracking', 'C++'],
    url: 'https://youtu.be/DKCtRlh0ES8',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-rec-cpp-learn',
    curriculumKey: 'DSA_RECURSION',
    language: 'C++',
    title: 'Striver: Recursion Playlist (Subsequences, Functional Recursion in C++)',
    provider: 'Striver',
    type: 'video',
    level: 'beginner',
    estimatedHours: 7,
    tags: ['Recursion', 'C++'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0rGlzIn_OIkfypgciR5K-61',
    free: true,
    order: 1,
    stage: 'learn',
  },
];

export const dsaSlidingWindowPointersResources: LibraryResource[] = [
  // ==================== SLIDING WINDOW ====================
  // Java
  {
    id: 'dsa-sw-java-learn',
    curriculumKey: 'DSA_SLIDING_WINDOW',
    language: 'Java',
    title: 'Striver: Sliding Window & Two Pointer Playlist in Java',
    provider: 'TakeUForward',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 7,
    tags: ['Sliding Window', 'Java', 'Substrings'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0q7ve7bK688sVyB1DX86Pry',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // Python
  {
    id: 'dsa-sw-py-learn',
    curriculumKey: 'DSA_SLIDING_WINDOW',
    language: 'Python',
    title: 'NeetCode Python: Sliding Window Pattern & Problem Solutions',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Sliding Window', 'Python'],
    url: 'https://youtu.be/UseZaYi80Ko',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // C++
  {
    id: 'dsa-sw-cpp-learn',
    curriculumKey: 'DSA_SLIDING_WINDOW',
    language: 'C++',
    title: 'Striver: Sliding Window Playlist in C++',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 7,
    tags: ['Sliding Window', 'C++'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0q7ve7bK688sVyB1DX86Pry',
    free: true,
    order: 1,
    stage: 'learn',
  },

  // ==================== TWO POINTERS ====================
  // Java
  {
    id: 'dsa-tp-java-learn',
    curriculumKey: 'DSA_TWO_POINTERS',
    language: 'Java',
    title: 'Kunal Kushwaha: Two Pointer Strategy & Array Subsets',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Two Pointers', 'Java'],
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7gFc1UMAxqv6t5P',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // Python
  {
    id: 'dsa-tp-py-learn',
    curriculumKey: 'DSA_TWO_POINTERS',
    language: 'Python',
    title: 'NeetCode Python: Two Pointers Pattern (3Sum, Container With Most Water)',
    provider: 'NeetCode',
    type: 'video',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Two Pointers', 'Python'],
    url: 'https://youtu.be/cQ1Oz4kDlh8',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // C++
  {
    id: 'dsa-tp-cpp-learn',
    curriculumKey: 'DSA_TWO_POINTERS',
    language: 'C++',
    title: 'Striver: Two Pointer Strategy and Array patterns',
    provider: 'TakeUForward',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Two Pointers', 'C++'],
    url: 'https://takeuforward.org/data-structure/trapping-rainwater/',
    free: true,
    order: 1,
    stage: 'learn',
  },
];
