import { LibraryResource } from '../types';

export const dsaHeapTrieResources: LibraryResource[] = [
  // ==================== HEAP ====================
  // Java
  {
    id: 'dsa-heap-java-learn',
    curriculumKey: 'DSA_HEAP',
    language: 'Java',
    title: 'Kunal Kushwaha: Heaps & PriorityQueue Data Structure in Java',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Heap', 'PriorityQueue', 'Java'],
    url: 'https://youtu.be/3dyJhGPQ57M',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-heap-java-practice',
    curriculumKey: 'DSA_HEAP',
    language: 'Java',
    title: 'Striver A2Z Heap Problems in Java (Kth Largest, Median of Stream)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Heap', 'Java'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-heap-py-learn',
    curriculumKey: 'DSA_HEAP',
    language: 'Python',
    title: 'NeetCode Python: Heap / Priority Queue Implementation (heapq)',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Heap', 'Python', 'heapq'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/23',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-heap-py-practice',
    curriculumKey: 'DSA_HEAP',
    language: 'Python',
    title: 'NeetCode 150 Heap Category Python Exercises',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Heap', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-heap-cpp-learn',
    curriculumKey: 'DSA_HEAP',
    language: 'C++',
    title: 'Abdul Bari: Heap Data Structure, Heapify & Heap Sort in C++',
    provider: 'Abdul Bari',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Heap', 'C++', 'Heapify'],
    url: 'https://youtu.be/H5kA3yIBBGQ',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-heap-cpp-practice',
    curriculumKey: 'DSA_HEAP',
    language: 'C++',
    title: 'Striver A2Z Heap Sheet C++: Task Scheduler & Top K Frequent Elements',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Heap', 'C++'],
    url: 'https://takeuforward.org/data-structure/kth-largest-element-in-an-array/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // ==================== TRIE ====================
  // Java
  {
    id: 'dsa-trie-java-learn',
    curriculumKey: 'DSA_TRIE',
    language: 'Java',
    title: 'Striver: Trie Data Structure Playlist & Implementation in Java',
    provider: 'TakeUForward',
    type: 'video',
    level: 'advanced',
    estimatedHours: 4,
    tags: ['Trie', 'Prefix Tree', 'Java'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0pcIDCZnxhv0NZJK5KQN0Yl',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // Python
  {
    id: 'dsa-trie-py-learn',
    curriculumKey: 'DSA_TRIE',
    language: 'Python',
    title: 'NeetCode: Prefix Trees (Trie) Tutorial & Python Implementation',
    provider: 'NeetCode',
    type: 'video',
    level: 'advanced',
    estimatedHours: 3,
    tags: ['Trie', 'Python'],
    url: 'https://youtu.be/oobqoRuObys',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // C++
  {
    id: 'dsa-trie-cpp-learn',
    curriculumKey: 'DSA_TRIE',
    language: 'C++',
    title: 'Striver: Trie Implementation I & II in C++',
    provider: 'Striver',
    type: 'video',
    level: 'advanced',
    estimatedHours: 4,
    tags: ['Trie', 'C++'],
    url: 'https://youtu.be/dBGUmUQhJaM',
    free: true,
    order: 1,
    stage: 'learn',
  },
];
