import { LibraryResource } from '../types';

export const dsaLinkedListResources: LibraryResource[] = [
  // Java
  {
    id: 'dsa-ll-java-learn',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'Java',
    title: 'Kunal Kushwaha: Singly & Doubly Linked List in Java',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Linked List', 'Java', 'Nodes', 'Pointers'],
    url: 'https://youtu.be/58YFWc5a9XA',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-ll-java-notes',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'Java',
    title: 'GeeksforGeeks: Java LinkedList Class vs Custom Node Implementation Notes',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Linked List', 'Java', 'Notes'],
    url: 'https://www.geeksforgeeks.org/linked-list-in-java/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-ll-java-practice',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'Java',
    title: 'Striver A2Z Linked List Sheet (Java): Reversing, Cycle Detection, Fast-Slow Pointers',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Linked List', 'Java', 'LeetCode'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-ll-java-interview',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'Java',
    title: 'Top Linked List Interview Questions (LRU Cache, Flattening a LinkedList in Java)',
    provider: 'TakeUForward',
    type: 'article',
    level: 'advanced',
    estimatedHours: 5,
    tags: ['Linked List', 'Java', 'Interview'],
    url: 'https://takeuforward.org/linked-list/flattening-a-linked-list/',
    free: true,
    order: 4,
    stage: 'interview',
  },

  // Python
  {
    id: 'dsa-ll-py-learn',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'Python',
    title: 'NeetCode Python: Singly, Doubly & Circular Linked Lists Implementation',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Linked List', 'Python'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/5',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-ll-py-notes',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'Python',
    title: 'Real Python: Python Linked Lists Implementation & Pointer Mechanics',
    provider: 'Real Python',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Linked List', 'Python', 'Notes'],
    url: 'https://realpython.com/linked-lists-python/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-ll-py-practice',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'Python',
    title: 'NeetCode 150 Linked List Python Problem Set',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Linked List', 'Python', 'LeetCode'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 3,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-ll-cpp-learn',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'C++',
    title: 'Striver: Singly & Doubly Linked Lists in C++ Complete Playlist',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Linked List', 'C++', 'Memory Management'],
    url: 'https://youtu.be/q8gdBn9RPeI',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-ll-cpp-notes',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'C++',
    title: 'Abdul Bari: Linked List Memory Allocation, Pointers & Operations in C++',
    provider: 'Abdul Bari',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Linked List', 'C++', 'Pointers'],
    url: 'https://youtu.be/NOVOUv7t004',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-ll-cpp-practice',
    curriculumKey: 'DSA_LINKED_LIST',
    language: 'C++',
    title: 'Striver A2Z Linked List Sheet (C++): Hard Problems (Merge K Lists, LRU Cache)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 10,
    tags: ['Linked List', 'C++', 'LRU Cache'],
    url: 'https://takeuforward.org/linked-list/lru-cache-implementation/',
    free: true,
    order: 3,
    stage: 'practice',
  },
];
