import { LibraryResource } from '../types';

export const dsaSortingResources: LibraryResource[] = [
  // Java
  {
    id: 'dsa-sort-java-learn',
    curriculumKey: 'DSA_SORTING',
    language: 'Java',
    title: 'Kunal Kushwaha: Bubble, Selection, Insertion, Merge, & Quick Sort in Java',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'beginner',
    estimatedHours: 6,
    tags: ['Sorting', 'Java', 'Merge Sort', 'Quick Sort'],
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7gFc1UMAxqv6t5P',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-sort-java-notes',
    curriculumKey: 'DSA_SORTING',
    language: 'Java',
    title: 'GeeksforGeeks Java Sorting Algorithms Space & Time Complexity Analysis',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Sorting', 'Java', 'Complexity'],
    url: 'https://www.geeksforgeeks.org/sorting-algorithms/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-sort-java-practice',
    curriculumKey: 'DSA_SORTING',
    language: 'Java',
    title: 'Striver A2Z Java Sorting Sheet: Custom Comparator & Dual Pivot Quick Sort',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Sorting', 'Java', 'Comparators'],
    url: 'https://takeuforward.org/sorting/selection-sort-algorithm/',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-sort-java-interview',
    curriculumKey: 'DSA_SORTING',
    language: 'Java',
    title: 'Top Sorting Interview Questions (Stable vs Unstable Sorts, In-Place Sorting)',
    provider: 'TakeUForward',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Sorting', 'Java', 'Interview'],
    url: 'https://takeuforward.org/sorting/quick-sort-algorithm/',
    free: true,
    order: 4,
    stage: 'interview',
  },

  // Python
  {
    id: 'dsa-sort-py-learn',
    curriculumKey: 'DSA_SORTING',
    language: 'Python',
    title: 'NeetCode Python: Sorting Algorithms (Bubble, Insertion, Merge, Quick)',
    provider: 'NeetCode',
    type: 'video',
    level: 'beginner',
    estimatedHours: 5,
    tags: ['Sorting', 'Python', 'Algorithms'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/12',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-sort-py-notes',
    curriculumKey: 'DSA_SORTING',
    language: 'Python',
    title: 'Real Python: Python Timsort Algorithm Internal Architecture',
    provider: 'Real Python',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 3,
    tags: ['Sorting', 'Python', 'Timsort'],
    url: 'https://realpython.com/sorting-algorithms-python/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-sort-py-practice',
    curriculumKey: 'DSA_SORTING',
    language: 'Python',
    title: 'GeeksforGeeks Python Sorting Practice Problems & Custom Lambda Keys',
    provider: 'GeeksforGeeks',
    type: 'practice',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Sorting', 'Python', 'Lambda'],
    url: 'https://www.geeksforgeeks.org/python-list-sort/',
    free: true,
    order: 3,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-sort-cpp-learn',
    curriculumKey: 'DSA_SORTING',
    language: 'C++',
    title: 'Striver: Sorting I & II (Bubble, Selection, Insertion, Merge, Quick Sort)',
    provider: 'Striver',
    type: 'video',
    level: 'beginner',
    estimatedHours: 5,
    tags: ['Sorting', 'C++', 'Divide and Conquer'],
    url: 'https://youtu.be/fBnsaEP4z74',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-sort-cpp-notes',
    curriculumKey: 'DSA_SORTING',
    language: 'C++',
    title: 'Abdul Bari: Analysis of Sorting Algorithms & Comparison Table',
    provider: 'Abdul Bari',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Sorting', 'C++', 'Comparison'],
    url: 'https://youtu.be/pkkFqlG0Hds',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-sort-cpp-practice',
    curriculumKey: 'DSA_SORTING',
    language: 'C++',
    title: 'Striver A2Z C++ Sheet: Merge Sort & Count Inversions in Array',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Sorting', 'C++', 'Inversions'],
    url: 'https://takeuforward.org/data-structure/count-inversions-in-an-array/',
    free: true,
    order: 3,
    stage: 'practice',
  },
];

export const dsaBinarySearchResources: LibraryResource[] = [
  // Java
  {
    id: 'dsa-bs-java-learn',
    curriculumKey: 'DSA_BINARY_SEARCH',
    language: 'Java',
    title: 'Kunal Kushwaha: Binary Search Playlist (Java 1D & 2D Arrays)',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Binary Search', 'Java', 'Boundaries'],
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7gFc1UMAxqv6t5P',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-bs-java-practice',
    curriculumKey: 'DSA_BINARY_SEARCH',
    language: 'Java',
    title: 'Striver A2Z Java Binary Search Sheet: Search on Answers & 2D Matrices',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Binary Search', 'Java', 'Search on Answers'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-bs-py-learn',
    curriculumKey: 'DSA_BINARY_SEARCH',
    language: 'Python',
    title: 'NeetCode Python: Binary Search Theory & LeetCode Problems',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Binary Search', 'Python', 'LeetCode'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/6',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-bs-py-practice',
    curriculumKey: 'DSA_BINARY_SEARCH',
    language: 'Python',
    title: 'NeetCode 150: Python Binary Search Category Solutions',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Binary Search', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-bs-cpp-learn',
    curriculumKey: 'DSA_BINARY_SEARCH',
    language: 'C++',
    title: 'Striver: Binary Search Complete Guide & Problem Sheet (C++)',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Binary Search', 'C++', 'Lower Bound', 'Upper Bound'],
    url: 'https://youtu.be/M3uVJgIh9oM',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-bs-cpp-practice',
    curriculumKey: 'DSA_BINARY_SEARCH',
    language: 'C++',
    title: 'Striver A2Z C++ Sheet: Aggressive Cows & Book Allocation Problems',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 8,
    tags: ['Binary Search', 'C++', 'Aggressive Cows'],
    url: 'https://takeuforward.org/data-structure/aggressive-cows-detailed-solution/',
    free: true,
    order: 2,
    stage: 'practice',
  },
];
