import { LibraryResource } from '../types';

export const dsaStacksQueuesResources: LibraryResource[] = [
  // ==================== STACKS ====================
  // Java
  {
    id: 'dsa-stack-java-learn',
    curriculumKey: 'DSA_STACK',
    language: 'Java',
    title: 'Kunal Kushwaha: Stacks & Queues in Java Complete Guide',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Stack', 'Queue', 'Java', 'Deque'],
    url: 'https://youtu.be/rIQgssEAHwA',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-stack-java-practice',
    curriculumKey: 'DSA_STACK',
    language: 'Java',
    title: 'Striver A2Z Java Stack Problems (Infix to Postfix, Valid Parentheses)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Stack', 'Java'],
    url: 'https://takeuforward.org/data-structure/stacks-and-queues-strivers-a2z-dsa-course-sheet/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-stack-py-learn',
    curriculumKey: 'DSA_STACK',
    language: 'Python',
    title: 'NeetCode Python: Stacks and Queues Implementation & LeetCode Practice',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Stack', 'Python', 'deque'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/8',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-stack-py-practice',
    curriculumKey: 'DSA_STACK',
    language: 'Python',
    title: 'NeetCode 150 Stack Python Category Exercises',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Stack', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-stack-cpp-learn',
    curriculumKey: 'DSA_STACK',
    language: 'C++',
    title: 'Striver: Stacks & Queues Basics to Monotonic Stack Sheet (C++)',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Stack', 'C++', 'Monotonic Stack'],
    url: 'https://takeuforward.org/data-structure/stacks-and-queues-strivers-a2z-dsa-course-sheet/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-stack-cpp-practice',
    curriculumKey: 'DSA_STACK',
    language: 'C++',
    title: 'Striver: Next Greater Element & Largest Rectangle in Histogram (C++)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 7,
    tags: ['Stack', 'C++', 'Histogram'],
    url: 'https://takeuforward.org/data-structure/next-greater-element-using-stack/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // ==================== QUEUES ====================
  // Java
  {
    id: 'dsa-queue-java-learn',
    curriculumKey: 'DSA_QUEUE',
    language: 'Java',
    title: 'Kunal Kushwaha: Circular Queue & Priority Queue in Java',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Queue', 'Java', 'PriorityQueue'],
    url: 'https://youtu.be/rIQgssEAHwA',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // Python
  {
    id: 'dsa-queue-py-learn',
    curriculumKey: 'DSA_QUEUE',
    language: 'Python',
    title: 'NeetCode Python: Queues & Monotonic Queue Problems',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Queue', 'Python', 'Monotonic Queue'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/8',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // C++
  {
    id: 'dsa-queue-cpp-learn',
    curriculumKey: 'DSA_QUEUE',
    language: 'C++',
    title: 'Striver: Queue & Circular Queue in C++ STL',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Queue', 'C++', 'STL'],
    url: 'https://takeuforward.org/data-structure/stacks-and-queues-strivers-a2z-dsa-course-sheet/',
    free: true,
    order: 1,
    stage: 'learn',
  },
];

export const dsaTreesBstResources: LibraryResource[] = [
  // ==================== TREES ====================
  // Java
  {
    id: 'dsa-tree-java-learn',
    curriculumKey: 'DSA_TREES',
    language: 'Java',
    title: 'Kunal Kushwaha: Binary Trees, BST, DFS, BFS (Java Complete Masterclass)',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Trees', 'Java', 'DFS', 'BFS'],
    url: 'https://youtu.be/f5zZ4yO1B20',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-tree-java-practice',
    curriculumKey: 'DSA_TREES',
    language: 'Java',
    title: 'Striver A2Z Binary Tree Sheet (Java Traversals, Boundary, Views)',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 10,
    tags: ['Trees', 'Java'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // Python
  {
    id: 'dsa-tree-py-learn',
    curriculumKey: 'DSA_TREES',
    language: 'Python',
    title: 'NeetCode Python: Binary Tree DFS & BFS Traversal',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Trees', 'Python', 'Traversal'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/17',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-tree-py-practice',
    curriculumKey: 'DSA_TREES',
    language: 'Python',
    title: 'NeetCode 150 Binary Trees Python Problems',
    provider: 'NeetCode',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Trees', 'Python'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // C++
  {
    id: 'dsa-tree-cpp-learn',
    curriculumKey: 'DSA_TREES',
    language: 'C++',
    title: 'Striver: Binary Tree Playlist (C++ Traversals, Views, Boundary)',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 10,
    tags: ['Trees', 'C++', 'Views'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0q8Hkd7bK2Bpryj2xVJk8Vk',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-tree-cpp-practice',
    curriculumKey: 'DSA_TREES',
    language: 'C++',
    title: 'Striver A2Z Tree Sheet (C++): Lowest Common Ancestor & Max Path Sum',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'advanced',
    estimatedHours: 10,
    tags: ['Trees', 'C++', 'LCA'],
    url: 'https://takeuforward.org/data-structure/lowest-common-ancestor-for-two-given-nodes/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // ==================== BST ====================
  // Java
  {
    id: 'dsa-bst-java-learn',
    curriculumKey: 'DSA_BST',
    language: 'Java',
    title: 'Striver: Binary Search Trees Operations & Problems in Java',
    provider: 'TakeUForward',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['BST', 'Java', 'Binary Search Tree'],
    url: 'https://youtu.be/pDKuiElg96Q',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // Python
  {
    id: 'dsa-bst-py-learn',
    curriculumKey: 'DSA_BST',
    language: 'Python',
    title: 'NeetCode Python: Binary Search Tree Insertion, Deletion & Search',
    provider: 'NeetCode',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['BST', 'Python'],
    url: 'https://neetcode.io/courses/dsa-for-beginners/19',
    free: true,
    order: 1,
    stage: 'learn',
  },
  // C++
  {
    id: 'dsa-bst-cpp-learn',
    curriculumKey: 'DSA_BST',
    language: 'C++',
    title: 'Striver: BST Complete Series in C++',
    provider: 'Striver',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['BST', 'C++'],
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0t4uB50iaYZbMleldE1S69y',
    free: true,
    order: 1,
    stage: 'learn',
  },
];
