import { LibraryResource } from '../types';

export const dsaStringsResources: LibraryResource[] = [
  // Java
  {
    id: 'dsa-str-java-learn',
    curriculumKey: 'DSA_STRINGS',
    language: 'Java',
    title: 'Kunal Kushwaha: Strings & StringBuilder in Java Complete Tutorial',
    provider: 'Kunal Kushwaha',
    type: 'video',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Strings', 'Java', 'String Pool', 'StringBuilder'],
    url: 'https://youtu.be/zL1DPZ0JVLo',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-str-java-notes',
    curriculumKey: 'DSA_STRINGS',
    language: 'Java',
    title: 'GeeksforGeeks: Java String Pool & Immutability Notes',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Strings', 'Java', 'Immutability'],
    url: 'https://www.geeksforgeeks.org/strings-in-java/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-str-java-practice',
    curriculumKey: 'DSA_STRINGS',
    language: 'Java',
    title: 'Striver A2Z Java String Sheet: Easy to Hard Problems',
    provider: 'TakeUForward',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['Strings', 'Java', 'Anagrams', 'Palindromes'],
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-str-java-interview',
    curriculumKey: 'DSA_STRINGS',
    language: 'Java',
    title: 'Top Java String Coding Interview Questions (Longest Palindromic Substring, Anagrams)',
    provider: 'TakeUForward',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Strings', 'Java', 'Interview'],
    url: 'https://takeuforward.org/string/longest-palindromic-substring-in-a-string/',
    free: true,
    order: 4,
    stage: 'interview',
  },
  {
    id: 'dsa-str-java-revision',
    curriculumKey: 'DSA_STRINGS',
    language: 'Java',
    title: 'Java String & Pattern Matching Cheat Sheet',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Strings', 'Java', 'Revision'],
    url: 'https://www.geeksforgeeks.org/java-string-methods/',
    free: true,
    order: 5,
    stage: 'revision',
  },

  // Python
  {
    id: 'dsa-str-py-learn',
    curriculumKey: 'DSA_STRINGS',
    language: 'Python',
    title: 'Corey Schafer: Python Strings, Slicing & String Methods',
    provider: 'Corey Schafer',
    type: 'video',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Strings', 'Python', 'Slicing'],
    url: 'https://youtu.be/k9TUPpGqYTo',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-str-py-notes',
    curriculumKey: 'DSA_STRINGS',
    language: 'Python',
    title: 'Real Python: Python String Formatting & Regex Guide',
    provider: 'Real Python',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Strings', 'Python', 'Regex'],
    url: 'https://realpython.com/python-strings/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-str-py-practice',
    curriculumKey: 'DSA_STRINGS',
    language: 'Python',
    title: 'GeeksforGeeks Python String Methods & Practice Questions',
    provider: 'GeeksforGeeks',
    type: 'practice',
    level: 'beginner',
    estimatedHours: 5,
    tags: ['Strings', 'Python', 'Methods'],
    url: 'https://www.geeksforgeeks.org/python-string-methods/',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-str-py-interview',
    curriculumKey: 'DSA_STRINGS',
    language: 'Python',
    title: 'NeetCode Python: Top String Problem Solutions & Pattern Matching',
    provider: 'NeetCode',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Strings', 'Python', 'Interview'],
    url: 'https://neetcode.io/practice',
    free: true,
    order: 4,
    stage: 'interview',
  },
  {
    id: 'dsa-str-py-revision',
    curriculumKey: 'DSA_STRINGS',
    language: 'Python',
    title: 'Python String Operations Cheat Sheet',
    provider: 'Real Python',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Strings', 'Python', 'Revision'],
    url: 'https://realpython.com/python-string-formatting/',
    free: true,
    order: 5,
    stage: 'revision',
  },

  // C++
  {
    id: 'dsa-str-cpp-learn',
    curriculumKey: 'DSA_STRINGS',
    language: 'C++',
    title: 'Striver DSA: Introduction to Strings & Character Arrays in C++',
    provider: 'Striver',
    type: 'video',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Strings', 'C++', 'std::string', 'ASCII'],
    url: 'https://youtu.be/58a1U5-Z-vM',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'dsa-str-cpp-notes',
    curriculumKey: 'DSA_STRINGS',
    language: 'C++',
    title: 'GeeksforGeeks: C++ std::string Class Operations & Memory Notes',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Strings', 'C++', 'Notes'],
    url: 'https://www.geeksforgeeks.org/stdstring-in-cpp-stl/',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'dsa-str-cpp-practice',
    curriculumKey: 'DSA_STRINGS',
    language: 'C++',
    title: 'Luv C++: Strings & Stringstreams in C++ Practice Problems',
    provider: 'Luv',
    type: 'practice',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Strings', 'C++', 'Stringstream'],
    url: 'https://youtu.be/lVv1e3bL33k',
    free: true,
    order: 3,
    stage: 'practice',
  },
  {
    id: 'dsa-str-cpp-interview',
    curriculumKey: 'DSA_STRINGS',
    language: 'C++',
    title: 'Top C++ String Interview Questions (Rabin-Karp, KMP Algorithm)',
    provider: 'TakeUForward',
    type: 'article',
    level: 'advanced',
    estimatedHours: 5,
    tags: ['Strings', 'C++', 'KMP', 'Rabin Karp'],
    url: 'https://takeuforward.org/string/kmp-algorithm-for-pattern-searching/',
    free: true,
    order: 4,
    stage: 'interview',
  },
  {
    id: 'dsa-str-cpp-revision',
    curriculumKey: 'DSA_STRINGS',
    language: 'C++',
    title: 'C++ std::string Functions & Stringstream Cheat Sheet',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['Strings', 'C++', 'Revision'],
    url: 'https://www.geeksforgeeks.org/c-plus-plus/',
    free: true,
    order: 5,
    stage: 'revision',
  },
];
