export const POPULAR_COLLEGES: string[] = [
  'Indian Institute of Technology (IIT) Bombay',
  'Indian Institute of Technology (IIT) Delhi',
  'Indian Institute of Technology (IIT) Madras',
  'Indian Institute of Technology (IIT) Kharagpur',
  'Indian Institute of Technology (IIT) Kanpur',
  'Indian Institute of Technology (IIT) Roorkee',
  'Indian Institute of Technology (IIT) Guwahati',
  'Indian Institute of Technology (IIT) Hyderabad',
  'Indian Institute of Technology (IIT) BHU Varanasi',
  'Indian Institute of Technology (IIT) Indore',
  'National Institute of Technology (NIT) Trichy',
  'National Institute of Technology (NIT) Surathkal',
  'National Institute of Technology (NIT) Warangal',
  'National Institute of Technology (NIT) Calicut',
  'National Institute of Technology (NIT) Rourkela',
  'International Institute of Information Technology (IIIT) Hyderabad',
  'International Institute of Information Technology (IIIT) Bangalore',
  'Indraprastha Institute of Information Technology (IIIT) Delhi',
  'BITS Pilani (Pilani Campus)',
  'BITS Pilani (Goa Campus)',
  'BITS Pilani (Hyderabad Campus)',
  'Delhi Technological University (DTU)',
  'Netaji Subhas University of Technology (NSUT)',
  'Jadavpur University, Kolkata',
  'College of Engineering Pune (COEP)',
  'Veermata Jijabai Technological Institute (VJTI) Mumbai',
  'RV College of Engineering (RVCE) Bengaluru',
  'BMS College of Engineering (BMSCE) Bengaluru',
  'PES University Bengaluru',
  'MS Ramaiah Institute of Technology (MSRIT) Bengaluru',
  'Vellore Institute of Technology (VIT) Vellore',
  'SRM Institute of Science and Technology, Chennai',
  'Manipal Institute of Technology (MIT) Manipal',
  'Thapar Institute of Engineering & Technology, Patiala',
  'PSG College of Technology, Coimbatore',
  'Amrita School of Engineering, Coimbatore',
  'Chandigarh University',
  'Lovely Professional University (LPU)',
  'Visvesvaraya Technological University (VTU)',
  'Anna University, Chennai',
];
