import { LibraryResource } from './types';

export const CURATED_RESOURCES: LibraryResource[] = [
  // ==========================================
  // 1. RECOMMENDED FOR YOU (Featured High-Quality)
  // ==========================================
  {
    id: 'rec-striver-dsa-a2z',
    title: "Striver's A2Z DSA Course & Placement Sheet",
    description: 'Complete step-by-step Data Structures & Algorithms roadmap with video solutions & practice problems by Striver.',
    provider: 'takeUforward / Striver',
    category: 'Recommended',
    topic: 'Data Structures & Algorithms',
    type: 'course',
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2',
    thumbnail: 'https://img.youtube.com/vi/0bHoB3etf1U/hqdefault.jpg',
    duration: '180+ Hours',
    level: 'Beginner',
    tags: ['DSA', 'Placement', 'LeetCode', 'Striver', 'Sheet'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'rec-fcc-python-full',
    title: 'Python Programming for Beginners - Full 12 Hour Course',
    description: 'Master Python fundamentals, object-oriented programming, file handling, and real-world scripting from scratch.',
    provider: 'freeCodeCamp',
    category: 'Recommended',
    topic: 'Python',
    type: 'playlist',
    url: 'https://www.youtube.com/watch?v=rfscVS0vUBs',
    thumbnail: 'https://img.youtube.com/vi/rfscVS0vUBs/hqdefault.jpg',
    duration: '12 Hours',
    level: 'Beginner',
    tags: ['Python', 'Programming', 'OOP', 'Scripts'],
    featured: true,
    language: 'Python',
    verified: true,
  },
  {
    id: 'rec-fcc-java-full',
    title: 'Java Programming Full Course for Beginners',
    description: 'Learn Java syntax, OOP principles, collection framework, memory management, and backend core concepts.',
    provider: 'freeCodeCamp',
    category: 'Recommended',
    topic: 'Java',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=A74TOX803D0',
    thumbnail: 'https://img.youtube.com/vi/A74TOX803D0/hqdefault.jpg',
    duration: '9.5 Hours',
    level: 'Beginner',
    tags: ['Java', 'OOP', 'Backend', 'Collections'],
    featured: true,
    language: 'Java',
    verified: true,
  },
  {
    id: 'rec-react-official-docs',
    title: 'React 18 Official Interactive Documentation & Guide',
    description: 'The official React documentation featuring interactive sandboxes, hooks deep-dive, and modern UI patterns.',
    provider: 'Official Docs',
    category: 'Recommended',
    topic: 'React',
    type: 'documentation',
    url: 'https://react.dev',
    thumbnail: 'https://react.dev/images/og-react.png',
    duration: 'Self-Paced',
    level: 'Intermediate',
    tags: ['React', 'Frontend', 'Hooks', 'JavaScript', 'UI'],
    featured: true,
    language: 'JavaScript',
    verified: true,
  },
  {
    id: 'rec-gate-smashers-os',
    title: 'Operating System Complete Playlist - Gate Smashers',
    description: 'Comprehensive OS course covering processes, CPU scheduling, deadlocks, memory management, and page replacement.',
    provider: 'Gate Smashers',
    category: 'Recommended',
    topic: 'Operating Systems',
    type: 'playlist',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p',
    thumbnail: 'https://img.youtube.com/vi/gA9D04P58E0/hqdefault.jpg',
    duration: '35 Videos',
    level: 'Beginner',
    tags: ['OS', 'CS Fundamentals', 'Processes', 'Deadlocks'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'rec-git-github-crash',
    title: 'Git & GitHub Complete Practical Course for Beginners',
    description: 'Learn Git version control, branching, merging, remote repositories, pull requests, and GitHub collaboration.',
    provider: 'Kunal Kushwaha / freeCodeCamp',
    category: 'Recommended',
    topic: 'Git & GitHub',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=apGV9Kg7ics',
    thumbnail: 'https://img.youtube.com/vi/apGV9Kg7ics/hqdefault.jpg',
    duration: '4 Hours',
    level: 'Beginner',
    tags: ['Git', 'GitHub', 'Version Control', 'Open Source'],
    featured: true,
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 2. PROGRAMMING LANGUAGES
  // ==========================================
  {
    id: 'lang-py-kannada-zero-to-hero',
    title: 'Python Zero to Hero Course in Kannada - Engineering in Kannada',
    description: 'Complete step-by-step Python programming playlist in Kannada covering basic syntax, data structures, OOPs, and hands-on coding from scratch.',
    provider: 'Engineering in Kannada',
    category: 'Programming Languages',
    topic: 'Python',
    type: 'playlist',
    url: 'https://www.youtube.com/watch?v=8c74mXV2lJ0&list=PLlGueSbLhZoBRnTsGiDJeTXuQCALOTN07',
    thumbnail: 'https://img.youtube.com/vi/8c74mXV2lJ0/hqdefault.jpg',
    duration: 'Full Playlist',
    level: 'Beginner',
    tags: ['Python', 'Kannada', 'Zero to Hero', 'Programming', 'Playlist', 'Engineering in Kannada'],
    featured: true,
    language: 'Python',
    verified: true,
  },
  {
    id: 'lang-py-1',
    title: 'Python for Everybody - University of Michigan',
    description: 'Learn Python programming, data structures, web scraping, databases, and data analysis fundamentals.',
    provider: 'freeCodeCamp / Dr. Chuck',
    category: 'Programming Languages',
    topic: 'Python',
    type: 'course',
    url: 'https://www.youtube.com/watch?v=8DvywoWv6fI',
    thumbnail: 'https://img.youtube.com/vi/8DvywoWv6fI/hqdefault.jpg',
    duration: '14 Hours',
    level: 'Beginner',
    tags: ['Python', 'Data Structures', 'Web Scraping'],
    language: 'Python',
    verified: true,
  },
  {
    id: 'lang-py-docs',
    title: 'Official Python 3 Documentation & Language Tutorial',
    description: 'Authoritative Python 3 documentation, language reference, standard library docs, and official tutorial.',
    provider: 'Official Docs',
    category: 'Programming Languages',
    topic: 'Python',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/index.html',
    thumbnail: 'https://docs.python.org/3/_static/py.png',
    duration: 'Reference',
    level: 'Beginner',
    tags: ['Python', 'Docs', 'Standard Library'],
    language: 'Python',
    verified: true,
  },
  {
    id: 'lang-java-1',
    title: 'Java Masterclass: OOP, Collections & Concurrency',
    description: 'In-depth Java tutorial covering object-oriented design, multithreading, JVM architecture, and stream API.',
    provider: 'Programming with Mosh',
    category: 'Programming Languages',
    topic: 'Java',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=eIrMbAQSU34',
    thumbnail: 'https://img.youtube.com/vi/eIrMbAQSU34/hqdefault.jpg',
    duration: '2.5 Hours',
    level: 'Beginner',
    tags: ['Java', 'OOP', 'JVM', 'Backend'],
    language: 'Java',
    verified: true,
  },
  {
    id: 'lang-cpp-1',
    title: 'C++ Programming Language Complete Course',
    description: 'Learn C++ syntax, pointers, memory allocation, STL containers, templates, and modern C++17/20 features.',
    provider: 'freeCodeCamp',
    category: 'Programming Languages',
    topic: 'C++',
    type: 'playlist',
    url: 'https://www.youtube.com/watch?v=vLnPwxZdW4Y',
    thumbnail: 'https://img.youtube.com/vi/vLnPwxZdW4Y/hqdefault.jpg',
    duration: '31 Hours',
    level: 'Beginner',
    tags: ['C++', 'STL', 'Pointers', 'DSA Language'],
    language: 'C++',
    verified: true,
  },
  {
    id: 'lang-js-1',
    title: 'Modern JavaScript ES6+ Full Course for Beginners',
    description: 'Master JavaScript closures, promises, async/await, DOM manipulation, event loop, and modern ES2023 syntax.',
    provider: 'freeCodeCamp',
    category: 'Programming Languages',
    topic: 'JavaScript',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=PkZNo7MFNFg',
    thumbnail: 'https://img.youtube.com/vi/PkZNo7MFNFg/hqdefault.jpg',
    duration: '3.5 Hours',
    level: 'Beginner',
    tags: ['JavaScript', 'ES6', 'Async', 'Web'],
    language: 'JavaScript',
    verified: true,
  },
  {
    id: 'lang-ts-1',
    title: 'TypeScript Full Course for Beginners',
    description: 'Learn static typing, interfaces, generics, type narrowers, union types, and TypeScript with React/Node.',
    provider: 'freeCodeCamp',
    category: 'Programming Languages',
    topic: 'TypeScript',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=30LWjhZ8V50',
    thumbnail: 'https://img.youtube.com/vi/30LWjhZ8V50/hqdefault.jpg',
    duration: '5 Hours',
    level: 'Intermediate',
    tags: ['TypeScript', 'Types', 'Generics', 'Frontend'],
    language: 'TypeScript',
    verified: true,
  },

  // ==========================================
  // 3. DATA STRUCTURES & ALGORITHMS (DSA)
  // ==========================================
  {
    id: 'dsa-neetcode-150',
    title: 'NeetCode 150 - Curated Coding Interview Roadmap',
    description: '150 handpicked LeetCode problems categorized by topic with video explanations and multi-language solutions.',
    provider: 'NeetCode',
    category: 'Data Structures & Algorithms',
    topic: 'DSA',
    type: 'practice',
    url: 'https://neetcode.io/practice',
    thumbnail: 'https://img.youtube.com/vi/KLlXCFG5TnA/hqdefault.jpg',
    duration: '150 Problems',
    level: 'Intermediate',
    tags: ['DSA', 'NeetCode', 'LeetCode', 'Interview'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'dsa-abdul-bari',
    title: 'Algorithms Analysis & Design - Abdul Bari',
    description: 'Legendary playlist covering Divide and Conquer, Greedy Method, Dynamic Programming, Backtracking, and Graph algorithms.',
    provider: 'Abdul Bari',
    category: 'Data Structures & Algorithms',
    topic: 'Algorithms',
    type: 'playlist',
    url: 'https://www.youtube.com/playlist?list=PLDN4rrl4ldRzJwZzL_7p196d-3kG3wF1A',
    thumbnail: 'https://img.youtube.com/vi/0IAPZzGSbME/hqdefault.jpg',
    duration: '84 Videos',
    level: 'Intermediate',
    tags: ['Algorithms', 'DP', 'Greedy', 'Graphs', 'Theory'],
    language: 'All',
    verified: true,
  },
  {
    id: 'dsa-leetcode-official',
    title: 'LeetCode Problem Solving & Contest Platform',
    description: 'The industry-standard platform for practicing DSA problems, participating in weekly contests, and mock interviews.',
    provider: 'LeetCode',
    category: 'Data Structures & Algorithms',
    topic: 'DSA Practice',
    type: 'practice',
    url: 'https://leetcode.com/problemset/all/',
    thumbnail: 'https://assets.leetcode.com/static_assets/public/images/LeetCode_Sharing.png',
    duration: '2500+ Problems',
    level: 'Intermediate',
    tags: ['LeetCode', 'Practice', 'Contests', 'Placement'],
    language: 'All',
    verified: true,
  },
  {
    id: 'dsa-gfg-hub',
    title: 'GeeksforGeeks Data Structures & Algorithms Hub',
    description: 'Comprehensive tutorials, code implementations in Java, Python, C++, and time complexity analyses.',
    provider: 'GeeksforGeeks',
    category: 'Data Structures & Algorithms',
    topic: 'DSA Notes',
    type: 'article',
    url: 'https://www.geeksforgeeks.org/data-structures/',
    thumbnail: 'https://media.geeksforgeeks.org/wp-content/uploads/20230810122244/dsa.png',
    duration: 'Reference',
    level: 'Beginner',
    tags: ['GeeksforGeeks', 'DSA', 'Notes', 'Complexity'],
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 4. WEB DEVELOPMENT
  // ==========================================
  {
    id: 'web-html-css-course',
    title: 'HTML & CSS Full Course - SuperSimpleDev',
    description: 'Learn modern HTML5, CSS3, Flexbox, CSS Grid, animations, and responsive web design hands-on.',
    provider: 'SuperSimpleDev',
    category: 'Web Development',
    topic: 'HTML & CSS',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=G3e-cpL7ofc',
    thumbnail: 'https://img.youtube.com/vi/G3e-cpL7ofc/hqdefault.jpg',
    duration: '6.5 Hours',
    level: 'Beginner',
    tags: ['HTML', 'CSS', 'Flexbox', 'Grid', 'Frontend'],
    language: 'JavaScript',
    verified: true,
  },
  {
    id: 'web-node-express-course',
    title: 'Node.js and Express.js Full Course - freeCodeCamp',
    description: 'Build backend APIs, express routing, middleware, authentication, MongoDB integration, and RESTful architectures.',
    provider: 'freeCodeCamp',
    category: 'Web Development',
    topic: 'Node.js & Backend',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
    thumbnail: 'https://img.youtube.com/vi/Oe421EPjeBE/hqdefault.jpg',
    duration: '8 Hours',
    level: 'Intermediate',
    tags: ['Node.js', 'Express', 'Backend', 'API', 'MongoDB'],
    language: 'JavaScript',
    verified: true,
  },
  {
    id: 'web-mongo-official-docs',
    title: 'MongoDB Developer Hub & Mongoose Guide',
    description: 'Official MongoDB manual covering document data modeling, aggregation pipelines, indexing, and Mongoose ORM.',
    provider: 'Official Docs',
    category: 'Web Development',
    topic: 'Databases',
    type: 'documentation',
    url: 'https://www.mongodb.com/docs/',
    thumbnail: 'https://webassets.mongodb.com/_com_assets/cms/mongodb_logo1-760240.png',
    duration: 'Reference',
    level: 'Intermediate',
    tags: ['MongoDB', 'NoSQL', 'Database', 'Mongoose'],
    language: 'JavaScript',
    verified: true,
  },

  // ==========================================
  // 5. CS FUNDAMENTALS
  // ==========================================
  {
    id: 'cs-dbms-gate-smashers',
    title: 'Database Management Systems (DBMS) - Gate Smashers',
    description: 'Learn SQL, ER diagrams, normalization (1NF-BCNF), transactions, ACID properties, indexing, and concurrency control.',
    provider: 'Gate Smashers',
    category: 'CS Fundamentals',
    topic: 'DBMS',
    type: 'playlist',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y',
    thumbnail: 'https://img.youtube.com/vi/3EJlovevfcA/hqdefault.jpg',
    duration: '50+ Videos',
    level: 'Beginner',
    tags: ['DBMS', 'SQL', 'Normalization', 'ACID'],
    language: 'All',
    verified: true,
  },
  {
    id: 'cs-cn-gate-smashers',
    title: 'Computer Networks Complete Course - Gate Smashers',
    description: 'Master OSI model, TCP/IP stack, IP addressing, subnetting, routing protocols, HTTP/HTTPS, and DNS.',
    provider: 'Gate Smashers',
    category: 'CS Fundamentals',
    topic: 'Computer Networks',
    type: 'playlist',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_',
    thumbnail: 'https://img.youtube.com/vi/VwN91x5i25g/hqdefault.jpg',
    duration: '60+ Videos',
    level: 'Beginner',
    tags: ['Computer Networks', 'OSI', 'TCP/IP', 'HTTP', 'DNS'],
    language: 'All',
    verified: true,
  },
  {
    id: 'cs-system-design-primer',
    title: 'The System Design Primer - GitHub Repository',
    description: 'An open-source roadmap for learning how to design large-scale systems (scalability, load balancing, caching, microservices).',
    provider: 'GitHub / Donne Martin',
    category: 'CS Fundamentals',
    topic: 'System Design',
    type: 'github',
    url: 'https://github.com/donnemartin/system-design-primer',
    thumbnail: 'https://repository-images.githubusercontent.com/82767873/59b15805-4c07-4e0e-953b-bc83d47d4e5f',
    duration: 'Open Source Repo',
    level: 'Advanced',
    tags: ['System Design', 'Scalability', 'Microservices', 'GitHub'],
    featured: true,
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 6. GIT & GITHUB
  // ==========================================
  {
    id: 'git-skills-official',
    title: 'GitHub Skills - Hands-on Interactive Learning Courses',
    description: 'Official GitHub interactive courses to learn Git, GitHub Pages, Pull Requests, Code Review, and GitHub Actions.',
    provider: 'GitHub Official',
    category: 'Git & GitHub',
    topic: 'Git & GitHub',
    type: 'open-source',
    url: 'https://skills.github.com/',
    thumbnail: 'https://skills.github.com/assets/images/github-skills-social.png',
    duration: 'Interactive Labs',
    level: 'Beginner',
    tags: ['Git', 'GitHub', 'GitHub Skills', 'Hands-on', 'PRs'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'git-learngitbranching',
    title: 'Learn Git Branching - Visual Command Simulator',
    description: 'An interactive visual game to master git commit, checkout, branch, rebase, merge, cherry-pick, and reset.',
    provider: 'LearnGitBranching',
    category: 'Git & GitHub',
    topic: 'Git Branching',
    type: 'practice',
    url: 'https://learngitbranching.js.org/',
    thumbnail: 'https://learngitbranching.js.org/assets/og.png',
    duration: 'Interactive Game',
    level: 'Beginner',
    tags: ['Git', 'Branching', 'Rebase', 'Interactive'],
    language: 'All',
    verified: true,
  },
  {
    id: 'git-progit-book',
    title: 'Pro Git Book - Free Official Git Documentation',
    description: 'The official free Git book covering internals, rebase techniques, hooks, server setup, and advanced workflows.',
    provider: 'Official Docs',
    category: 'Git & GitHub',
    topic: 'Git Internals',
    type: 'documentation',
    url: 'https://git-scm.com/book/en/v2',
    thumbnail: 'https://git-scm.com/images/progit2.png',
    duration: 'Book / Reference',
    level: 'Intermediate',
    tags: ['Git', 'Book', 'Internals', 'Workflows'],
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 7. OPEN SOURCE & GSOC
  // ==========================================
  {
    id: 'gsoc-student-guide',
    title: 'Google Summer of Code (GSoC) Official Contributor Guide',
    description: 'Official student guide covering GSoC eligibility, organization selection, proposal writing, and mentor communication.',
    provider: 'Google Open Source',
    category: 'Open Source & GSoC',
    topic: 'GSoC',
    type: 'documentation',
    url: 'https://google.github.io/gsocguides/student/',
    thumbnail: 'https://summerofcode.withgoogle.com/static/assets/media/gsoc-2024-social-share.png',
    duration: 'Official Guide',
    level: 'Beginner',
    tags: ['GSoC', 'Google', 'Open Source', 'Proposal', 'Mentorship'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'gsoc-first-contributions',
    title: 'First Contributions - Make Your First Open Source PR',
    description: 'A hands-on GitHub repository designed to guide beginners through making their very first open-source pull request in 5 minutes.',
    provider: 'First Contributions',
    category: 'Open Source & GSoC',
    topic: 'First Contribution',
    type: 'github',
    url: 'https://github.com/firstcontributions/first-contributions',
    thumbnail: 'https://repository-images.githubusercontent.com/107008719/7e923e00-7521-11e9-9a2f-e8b2b109e450',
    duration: '5 Mins Hands-on',
    level: 'Beginner',
    tags: ['Open Source', 'GitHub', 'Pull Request', 'First Contribution'],
    language: 'All',
    verified: true,
  },
  {
    id: 'gsoc-kunal-complete-guide',
    title: 'Complete Open Source & GSoC Roadmap by Kunal Kushwaha',
    description: 'Comprehensive video guide explaining open-source workflow, organization research, GSoC proposals, and community interaction.',
    provider: 'Kunal Kushwaha',
    category: 'Open Source & GSoC',
    topic: 'Open Source Guide',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=msyGyyZP1Lo',
    thumbnail: 'https://img.youtube.com/vi/msyGyyZP1Lo/hqdefault.jpg',
    duration: '1.5 Hours',
    level: 'Beginner',
    tags: ['GSoC', 'Open Source', 'Community', 'Proposals'],
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 8. APTITUDE
  // ==========================================
  {
    id: 'apt-gfg-math',
    title: 'Quantitative Aptitude Preparation Guide for Placements',
    description: 'Step-by-step math topics: percentages, profit & loss, time & work, probability, permutations, speed & distance.',
    provider: 'GeeksforGeeks',
    category: 'Aptitude',
    topic: 'Quantitative Aptitude',
    type: 'article',
    url: 'https://www.geeksforgeeks.org/quantitative-aptitude-maths/',
    thumbnail: 'https://media.geeksforgeeks.org/wp-content/uploads/20230303125219/Aptitude-1.png',
    duration: 'Study Guide',
    level: 'Beginner',
    tags: ['Aptitude', 'Quantitative', 'Placement', 'Maths'],
    language: 'All',
    verified: true,
  },
  {
    id: 'apt-indiabix-reasoning',
    title: 'Logical Reasoning Questions & Explanations - IndiaBIX',
    description: 'Topic-wise practice questions for blood relations, coding-decoding, number series, seating arrangements, and syllogisms.',
    provider: 'IndiaBIX',
    category: 'Aptitude',
    topic: 'Logical Reasoning',
    type: 'practice',
    url: 'https://www.indiabix.com/logical-reasoning/questions-and-answers/',
    thumbnail: 'https://www.indiabix.com/_files/images/indiabix-logo.png',
    duration: 'Practice Sets',
    level: 'Beginner',
    tags: ['Logical Reasoning', 'Aptitude', 'IndiaBIX', 'Placements'],
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 9. INTERVIEW PREPARATION
  // ==========================================
  {
    id: 'int-striver-sde-sheet',
    title: "Striver's SDE Sheet - Top 180 Coding Interview Problems",
    description: 'The most popular coding interview preparation sheet used by top candidates to crack product companies.',
    provider: 'takeUforward / Striver',
    category: 'Interview Preparation',
    topic: 'DSA Interview',
    type: 'interview',
    url: 'https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/',
    thumbnail: 'https://img.youtube.com/vi/0bHoB3etf1U/hqdefault.jpg',
    duration: '180 Problems',
    level: 'Intermediate',
    tags: ['SDE Sheet', 'Striver', 'Interviews', 'LeetCode'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'int-tech-interview-handbook',
    title: 'Tech Interview Handbook by Yangshun Tay',
    description: 'Free curated guide for tech interviews: coding patterns, behavioral STAR method, resume tips, and salary negotiation.',
    provider: 'Yangshun Tay',
    category: 'Interview Preparation',
    topic: 'Tech Interview',
    type: 'article',
    url: 'https://www.techinterviewhandbook.org/',
    thumbnail: 'https://www.techinterviewhandbook.org/img/social-card.png',
    duration: 'Complete Handbook',
    level: 'Intermediate',
    tags: ['Interview', 'Resume', 'Behavioral', 'STAR Method'],
    language: 'All',
    verified: true,
  },
  {
    id: 'int-sql-50-leetcode',
    title: 'Top 50 SQL Interview Questions - LeetCode Study Plan',
    description: 'Master SQL joins, group by, subqueries, window functions, and database query optimization for technical interviews.',
    provider: 'LeetCode',
    category: 'Interview Preparation',
    topic: 'SQL Interview',
    type: 'practice',
    url: 'https://leetcode.com/studyplan/top-sql-50/',
    thumbnail: 'https://assets.leetcode.com/static_assets/public/images/LeetCode_Sharing.png',
    duration: '50 Queries',
    level: 'Intermediate',
    tags: ['SQL', 'Database', 'LeetCode', 'Interview'],
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 10. PROJECTS
  // ==========================================
  {
    id: 'proj-mern-ecommerce',
    title: 'Full Stack MERN E-Commerce Web Application Project',
    description: 'Build a production-ready E-commerce website with React, Node.js, Express, MongoDB, Redux Toolkit, and Stripe payments.',
    provider: 'freeCodeCamp',
    category: 'Projects',
    topic: 'MERN Stack',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=CDtPbsAsjbc',
    thumbnail: 'https://img.youtube.com/vi/CDtPbsAsjbc/hqdefault.jpg',
    duration: '12 Hours',
    level: 'Advanced',
    tags: ['MERN', 'React', 'Node.js', 'Project', 'E-Commerce'],
    featured: true,
    language: 'JavaScript',
    verified: true,
  },
  {
    id: 'proj-ai-saas-next',
    title: 'Build and Deploy a Full Stack AI SaaS Application',
    description: 'Construct an AI-powered SaaS application using Next.js 14, TypeScript, Tailwind CSS, OpenAI / Gemini API, and Stripe billing.',
    provider: 'JavaScript Mastery',
    category: 'Projects',
    topic: 'AI SaaS',
    type: 'video',
    url: 'https://www.youtube.com/watch?v=ahCwqrYpIuY',
    thumbnail: 'https://img.youtube.com/vi/ahCwqrYpIuY/hqdefault.jpg',
    duration: '10 Hours',
    level: 'Advanced',
    tags: ['Next.js', 'AI', 'SaaS', 'TypeScript', 'Stripe'],
    featured: true,
    language: 'TypeScript',
    verified: true,
  },
  {
    id: 'proj-app-ideas-github',
    title: 'App Ideas Collection - GitHub Open Source Repository',
    description: 'A curated collection of practical project ideas categorized by Tier (Beginner, Intermediate, Advanced) with full spec requirements.',
    provider: 'GitHub / Florin Pop',
    category: 'Projects',
    topic: 'Project Ideas',
    type: 'github',
    url: 'https://github.com/florinpop17/app-ideas',
    thumbnail: 'https://repository-images.githubusercontent.com/167232230/920f0680-60b2-11e9-9139-44cb7b11d8e7',
    duration: 'Project Repository',
    level: 'Beginner',
    tags: ['Projects', 'GitHub', 'Portfolio', 'Specs'],
    language: 'All',
    verified: true,
  },

  // ==========================================
  // 11. DEVOPS & CLOUD
  // ==========================================
  {
    id: 'yt-devops-fundamentals-day1',
    title: 'Day-1: Fundamentals of DevOps - Complete Masterclass',
    description: 'Learn foundational DevOps concepts, software development lifecycle, automation, cloud infrastructure, and culture from scratch by Abhishek Veeramalla.',
    provider: 'Abhishek Veeramalla',
    category: 'CS Fundamentals',
    topic: 'DevOps & Cloud',
    type: 'video',
    url: 'https://youtu.be/Ou9j73aWgyE?si=WkPHjcaizxws3sVg',
    thumbnail: 'https://img.youtube.com/vi/Ou9j73aWgyE/hqdefault.jpg',
    duration: 'Full Lecture',
    level: 'Beginner',
    tags: ['DevOps', 'CI/CD', 'Cloud', 'Infrastructure', 'Linux', 'Automation'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-kubernetes-introduction-day30',
    title: 'Day-30: Introduction to Kubernetes (K8s) - Kubernetes Made Easy',
    description: 'Master Kubernetes architecture, pods, deployments, services, container orchestration, and cluster management in simple terms.',
    provider: 'Abhishek Veeramalla',
    category: 'CS Fundamentals',
    topic: 'Kubernetes (K8s)',
    type: 'video',
    url: 'https://youtu.be/dfxrdoEQe00?si=XqalogGTLsap8N4A',
    thumbnail: 'https://img.youtube.com/vi/dfxrdoEQe00/hqdefault.jpg',
    duration: 'Full Lecture',
    level: 'Intermediate',
    tags: ['Kubernetes', 'K8s', 'Docker', 'Containers', 'DevOps', 'Orchestration'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-docker-containers-day23',
    title: 'Day-23: Introduction to Containers & Docker Architecture',
    description: 'Learn what containers are, Docker fundamentals, images, container lifecycle, volumes, and networking in an easy practical guide.',
    provider: 'Abhishek Veeramalla',
    category: 'CS Fundamentals',
    topic: 'Docker & Containers',
    type: 'video',
    url: 'https://youtu.be/7JZP345yVjw?si=q7PF3gGtUrJe3TfI',
    thumbnail: 'https://img.youtube.com/vi/7JZP345yVjw/hqdefault.jpg',
    duration: 'Full Lecture',
    level: 'Beginner',
    tags: ['Docker', 'Containers', 'DevOps', 'Architecture', 'Deployment'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-cicd-introduction-day18',
    title: 'Day-18: What is CI/CD? Complete Introduction & Architecture',
    description: 'Understand Continuous Integration and Continuous Deployment (CI/CD) pipelines, build automation, testing integration, and release workflows.',
    provider: 'Abhishek Veeramalla',
    category: 'CS Fundamentals',
    topic: 'CI/CD Pipelines',
    type: 'video',
    url: 'https://youtu.be/CmVxoNkkACQ?si=5hH79LQ93eiYJIyU',
    thumbnail: 'https://img.youtube.com/vi/CmVxoNkkACQ/hqdefault.jpg',
    duration: 'Full Lecture',
    level: 'Beginner',
    tags: ['CI/CD', 'Jenkins', 'GitHub Actions', 'DevOps', 'Automation', 'Pipeline'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-remote-job-guide-sanskar',
    title: 'Watch This To Get a Remote Job (5-Step Action Checklist)',
    description: 'Practical 5-step checklist for engineering students and developers to land international remote software engineering jobs.',
    provider: 'The Sanskar Show',
    category: 'Interview Preparation',
    topic: 'Remote Jobs & Career',
    type: 'video',
    url: 'https://youtu.be/GR8TlBdeiXY?si=aXx73ykLeaZ1PaN1',
    thumbnail: 'https://img.youtube.com/vi/GR8TlBdeiXY/hqdefault.jpg',
    duration: 'Full Guide',
    level: 'Beginner',
    tags: ['Remote Jobs', 'Career Guidance', 'Placement', 'Interviews', 'Job Search'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-dp-intro-aditya-verma',
    title: 'Dynamic Programming | Introduction & Core Concepts',
    description: 'Master Dynamic Programming identification patterns, memoization vs tabulation, subproblem breakdowns, and decision trees by Aditya Verma.',
    provider: 'Aditya Verma',
    category: 'Data Structures & Algorithms',
    topic: 'Dynamic Programming',
    type: 'video',
    url: 'https://youtu.be/nqowUJzG-iM?si=hgAy2UbI011CFl-X',
    thumbnail: 'https://img.youtube.com/vi/nqowUJzG-iM/hqdefault.jpg',
    duration: 'Full Lecture',
    level: 'Intermediate',
    tags: ['Dynamic Programming', 'DP', 'DSA', 'Aditya Verma', 'Placement', 'LeetCode'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-claude-code-zero-to-hero',
    title: 'Claude Code Zero to Hero in 60 Minutes',
    description: 'Comprehensive 60-minute crash course on leveraging Claude Code AI for software development, terminal workflows, refactoring, and dev automation.',
    provider: 'Abhishek Veeramalla',
    category: 'Programming Languages',
    topic: 'AI & Developer Tooling',
    type: 'video',
    url: 'https://youtu.be/GQ1SJf67nKw?si=0mgzCB4HA46zpNaG',
    thumbnail: 'https://img.youtube.com/vi/GQ1SJf67nKw/hqdefault.jpg',
    duration: '60 Minutes',
    level: 'Beginner',
    tags: ['Claude Code', 'AI Tools', 'DevOps', 'Automation', 'Anthropic', 'Prompting'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-fde-roadmap-20min',
    title: 'Forward Deployed Engineer (FDE) Roadmap in 20 Minutes',
    description: 'Complete 20-minute breakdown of Forward Deployed Engineering: skills, client architecture, technical problem solving, and career growth roadmap by Abhishek Veeramalla.',
    provider: 'Abhishek Veeramalla',
    category: 'Interview Preparation',
    topic: 'Forward Deployed Engineering',
    type: 'video',
    url: 'https://youtu.be/SOU28VT-Ns4?si=lehqo7NYQCOZptvN',
    thumbnail: 'https://img.youtube.com/vi/SOU28VT-Ns4/hqdefault.jpg',
    duration: '20 Minutes',
    level: 'Beginner',
    tags: ['Forward Deployed Engineer', 'FDE', 'Career Roadmap', 'DevOps', 'Solutions Architect', 'Tech Careers'],
    featured: true,
    language: 'All',
    verified: true,
  },
  {
    id: 'yt-kunal-dsa-course',
    title: 'Best Data Structures & Algorithms (DSA) Course - Clear Any FAANG Interview!',
    description: 'Complete Data Structures & Algorithms masterclass covering Java, Time Complexity, Recursion, Trees, Graphs, and FAANG coding interview prep by Kunal Kushwaha.',
    provider: 'Kunal Kushwaha',
    category: 'Data Structures & Algorithms',
    topic: 'DSA & FAANG Preparation',
    type: 'course',
    url: 'https://youtu.be/rZ41y93P2Qo?si=3eSum3ocZpwUXpgw',
    thumbnail: 'https://img.youtube.com/vi/rZ41y93P2Qo/hqdefault.jpg',
    duration: 'Full Course',
    level: 'Beginner',
    tags: ['DSA', 'Kunal Kushwaha', 'Java', 'FAANG', 'Data Structures', 'Algorithms', 'Placement'],
    featured: true,
    language: 'Java',
    verified: true,
  },
  {
    id: 'yt-careerride-aptitude-channel',
    title: 'CareerRide - Complete Quantitative & Logical Aptitude Course Channel',
    description: 'Comprehensive Aptitude, Logical Reasoning, Verbal Ability, and Interview Preparation tutorials and practice tests for campus placements by CareerRide.',
    provider: 'CareerRide Official',
    category: 'Aptitude',
    topic: 'Quantitative & Logical Aptitude',
    type: 'course',
    url: 'https://www.youtube.com/@CareerRideOfficial',
    thumbnail: 'https://img.youtube.com/vi/5qap5aO4i9A/hqdefault.jpg',
    duration: 'Full Aptitude Series',
    level: 'Beginner',
    tags: ['Aptitude', 'Logical Reasoning', 'CareerRide', 'Placements', 'Quants', 'Verbal'],
    featured: true,
    language: 'All',
    verified: true,
  },
];
