import { LibraryResource } from '../types';

export const interviewResources: LibraryResource[] = [
  // ==================== RESUME, ATS, LINKEDIN ====================
  {
    id: 'int-resume-learn-1',
    curriculumKey: 'INT_RESUME',
    language: 'All',
    title: 'Google Official Tech Resume Guide: Formatting, Action Verbs & Impact Bullet Points',
    provider: 'Google Guides',
    type: 'article',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Resume', 'Google', 'ATS', 'Impact'],
    url: 'https://www.freecodecamp.org/news/how-to-write-a-tech-resume/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'int-resume-learn-2',
    curriculumKey: 'INT_RESUME',
    language: 'All',
    title: 'Harvard Resume & Cover Letter Complete Guide for Computer Science Students',
    provider: 'Harvard Guides',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Resume', 'Harvard', 'Formatting'],
    url: 'https://cdn-careerservices.fas.harvard.edu/wp-content/uploads/sites/161/2023/04/2023-resume-and-cover-letter-guide.pdf',
    free: true,
    order: 2,
    stage: 'notes',
  },
  {
    id: 'int-ats-learn-1',
    curriculumKey: 'INT_ATS',
    language: 'All',
    title: 'ResumeWorded: Free ATS Resume Checker & Keyword Match Optimization',
    provider: 'ResumeWorded',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['ATS', 'Resume', 'Keywords'],
    url: 'https://resumeworded.com',
    free: true,
    order: 1,
    stage: 'practice',
  },
  {
    id: 'int-linkedin-learn-1',
    curriculumKey: 'INT_LINKEDIN',
    language: 'All',
    title: 'LinkedIn Profile Optimization Guide for Software Engineers & Recruiter Outreach',
    provider: 'FreeCodeCamp',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['LinkedIn', 'Networking', 'Recruiters'],
    url: 'https://www.freecodecamp.org/news/linkedin-profile-optimization-for-developers/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'int-github-learn-1',
    curriculumKey: 'INT_RESUME',
    language: 'All',
    title: 'GitHub Profile README & Open Source Portfolio Showcase Guide',
    provider: 'FreeCodeCamp',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['GitHub', 'Portfolio', 'Open Source'],
    url: 'https://www.freecodecamp.org/news/how-to-create-a-great-github-profile-readme/',
    free: true,
    order: 3,
    stage: 'practice',
  },

  // ==================== HR & BEHAVIORAL ====================
  {
    id: 'int-beh-learn-1',
    curriculumKey: 'INT_BEHAVIORAL',
    language: 'All',
    title: 'STAR Method Masterclass for Software Engineer Behavioral Interviews',
    provider: 'FreeCodeCamp',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Behavioral', 'STAR Method', 'HR Interview', 'Leadership'],
    url: 'https://youtu.be/8m1fFm1gXsc',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'int-hr-learn-1',
    curriculumKey: 'INT_HR',
    language: 'All',
    title: 'Top HR & Behavioral Questions asked at Product-Based & Service-Based Companies',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['HR', 'Behavioral', 'Soft Skills'],
    url: 'https://www.geeksforgeeks.org/hr-interview-questions/',
    free: true,
    order: 1,
    stage: 'interview',
  },
  {
    id: 'int-comm-learn-1',
    curriculumKey: 'INT_HR',
    language: 'All',
    title: 'Technical Communication & Salary Negotiation Guide for Software Engineers',
    provider: 'FreeCodeCamp',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Communication', 'Salary Negotiation', 'Soft Skills'],
    url: 'https://www.freecodecamp.org/news/how-to-negotiate-a-job-offer/',
    free: true,
    order: 2,
    stage: 'interview',
  },

  // ==================== MOCK INTERVIEWS ====================
  {
    id: 'int-mock-learn-1',
    curriculumKey: 'INT_MOCK',
    language: 'All',
    title: 'Pramp: Free Peer-to-Peer Mock Interviews for Data Structures, Algorithms & System Design',
    provider: 'Pramp',
    type: 'interactive',
    level: 'advanced',
    estimatedHours: 10,
    tags: ['Mock Interview', 'Peer-to-Peer', 'Live Coding'],
    url: 'https://www.pramp.com',
    free: true,
    order: 1,
    stage: 'practice',
  },
  {
    id: 'int-mock-learn-2',
    curriculumKey: 'INT_MOCK',
    language: 'All',
    title: 'Interviewing.io: Free Anonymized Tech Mock Interviews & Senior Engineer Feedback',
    provider: 'Interviewing.io',
    type: 'article',
    level: 'advanced',
    estimatedHours: 6,
    tags: ['Mock Interview', 'FAANG', 'Feedback'],
    url: 'https://interviewing.io',
    free: true,
    order: 2,
    stage: 'interview',
  },
];
