import { LibraryResource } from '../types';

export const webBackendResources: LibraryResource[] = [
  // ==================== NODE.JS & EXPRESS ====================
  {
    id: 'web-node-learn-1',
    curriculumKey: 'DEV_NODE',
    language: 'JavaScript',
    title: 'Official Node.js Documentation & Event Loop Architecture Guide',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 10,
    tags: ['Node.js', 'Event Loop', 'Asynchronous I/O', 'Streams'],
    url: 'https://nodejs.org/en/docs/guides/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-node-learn-2',
    curriculumKey: 'DEV_NODE',
    language: 'JavaScript',
    title: 'FreeCodeCamp: Node.js and Express.js Full Course (8 Hours)',
    provider: 'FreeCodeCamp',
    type: 'video',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['Node.js', 'Express', 'Backend'],
    url: 'https://youtu.be/Oe421EPjeBE',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'web-express-learn',
    curriculumKey: 'DEV_EXPRESS',
    language: 'JavaScript',
    title: 'Official Express.js Routing & Middleware Guide',
    provider: 'Official Docs',
    type: 'article',
    level: 'beginner',
    estimatedHours: 6,
    tags: ['Express', 'Routing', 'Middleware', 'REST API'],
    url: 'https://expressjs.com/en/starter/installing.html',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-express-practice',
    curriculumKey: 'DEV_EXPRESS',
    language: 'JavaScript',
    title: 'GeeksforGeeks: Express.js Middleware & Error Handling Patterns',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Express', 'Middleware', 'Error Handling'],
    url: 'https://www.geeksforgeeks.org/express-js-middleware/',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // ==================== REST APIS, AUTH, JWT, COOKIES ====================
  {
    id: 'web-rest-learn',
    curriculumKey: 'DEV_REST_APIS',
    language: 'All',
    title: 'MDN Web Docs: RESTful API Design Principles & HTTP Methods',
    provider: 'MDN',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['REST API', 'HTTP', 'JSON', 'Status Codes'],
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-auth-learn',
    curriculumKey: 'DEV_AUTHENTICATION',
    language: 'All',
    title: 'Auth0: Introduction to JSON Web Tokens (JWT) & Security Best Practices',
    provider: 'Auth0',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['Auth', 'JWT', 'Security', 'Cookies', 'Sessions'],
    url: 'https://jwt.io/introduction',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-cookies-learn',
    curriculumKey: 'DEV_COOKIES',
    language: 'All',
    title: 'MDN Web Docs: HTTP Cookies, SameSite & Session Security',
    provider: 'MDN',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 4,
    tags: ['Cookies', 'HTTP', 'Security'],
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies',
    free: true,
    order: 1,
    stage: 'learn',
  },
];

export const webDatabasesResources: LibraryResource[] = [
  // ==================== MONGODB ====================
  {
    id: 'web-mongo-learn-1',
    curriculumKey: 'DEV_MONGODB',
    language: 'All',
    title: 'MongoDB University: M001 MongoDB Basics (Free Official Certification Course)',
    provider: 'MongoDB University',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 12,
    tags: ['MongoDB', 'NoSQL', 'Aggregation', 'Mongoose'],
    url: 'https://learn.mongodb.com/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-mongo-learn-2',
    curriculumKey: 'DEV_MONGODB',
    language: 'All',
    title: 'Official MongoDB Manual & CRUD Operations Documentation',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['MongoDB', 'Docs'],
    url: 'https://www.mongodb.com/docs/manual/',
    free: true,
    order: 2,
    stage: 'learn',
  },

  // ==================== SQL ====================
  {
    id: 'web-sql-learn-1',
    curriculumKey: 'DEV_SQL',
    language: 'All',
    title: 'SQLZoo: Interactive SQL Tutorials & Complex Queries Practice',
    provider: 'SQLZoo',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 10,
    tags: ['SQL', 'JOINs', 'Subqueries', 'Group By'],
    url: 'https://sqlzoo.net',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-sql-learn-2',
    curriculumKey: 'DEV_SQL',
    language: 'All',
    title: 'Mode Analytics: Mode SQL Tutorial for Data Analysis & Engineers',
    provider: 'Mode',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['SQL', 'Database'],
    url: 'https://mode.com/sql-tutorial/',
    free: true,
    order: 2,
    stage: 'learn',
  },

  // ==================== REDIS & CACHING ====================
  {
    id: 'web-redis-learn',
    curriculumKey: 'DEV_REDIS',
    language: 'All',
    title: 'Official Redis Documentation & In-Memory Caching Architecture',
    provider: 'Official Docs',
    type: 'article',
    level: 'advanced',
    estimatedHours: 6,
    tags: ['Redis', 'Caching', 'In-Memory'],
    url: 'https://redis.io/docs/',
    free: true,
    order: 1,
    stage: 'learn',
  },
];

export const webDevopsResources: LibraryResource[] = [
  // Docker
  {
    id: 'web-docker-learn-1',
    curriculumKey: 'DEV_DOCKER',
    language: 'All',
    title: 'Official Docker Documentation & Getting Started Guide',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Docker', 'Containers', 'Dockerfile', 'Docker Compose'],
    url: 'https://docs.docker.com/get-started/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-docker-learn-2',
    curriculumKey: 'DEV_DOCKER',
    language: 'All',
    title: 'FreeCodeCamp: Docker Tutorial for Beginners',
    provider: 'FreeCodeCamp',
    type: 'video',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Docker', 'DevOps'],
    url: 'https://youtu.be/fqMOX6JJhGo',
    free: true,
    order: 2,
    stage: 'learn',
  },

  // Deployment & AWS
  {
    id: 'web-deployment-learn',
    curriculumKey: 'DEV_DEPLOYMENT',
    language: 'All',
    title: 'Vercel & Render Official Deployment Guides for Full-Stack Apps',
    provider: 'Vercel',
    type: 'article',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Deployment', 'Vercel', 'Render', 'CI/CD'],
    url: 'https://vercel.com/docs',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-aws-learn',
    curriculumKey: 'DEV_AWS',
    language: 'All',
    title: 'AWS Skill Builder: Official Free Cloud Practitioner & S3/EC2 Essentials',
    provider: 'Official Docs',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 10,
    tags: ['AWS', 'Cloud', 'EC2', 'S3'],
    url: 'https://aws.amazon.com/training/skills-builder/',
    free: true,
    order: 1,
    stage: 'learn',
  },

  // CI/CD
  {
    id: 'web-cicd-learn',
    curriculumKey: 'DEV_CICD',
    language: 'All',
    title: 'GitHub Actions Official Documentation: Continuous Integration & Deployment',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['CI/CD', 'GitHub Actions', 'DevOps'],
    url: 'https://docs.github.com/en/actions',
    free: true,
    order: 1,
    stage: 'learn',
  },
];
