import { LibraryResource } from '../types';

export const webFrontendResources: LibraryResource[] = [
  // ==================== HTML ====================
  {
    id: 'web-html-learn-1',
    curriculumKey: 'DEV_HTML',
    language: 'JavaScript',
    title: 'MDN Web Docs: Learn HTML Structure & Semantic Elements',
    provider: 'MDN',
    type: 'article',
    level: 'beginner',
    estimatedHours: 6,
    tags: ['HTML', 'Semantics', 'Accessibility'],
    url: 'https://developer.mozilla.org/en-US/docs/Learn/HTML',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-html-learn-2',
    curriculumKey: 'DEV_HTML',
    language: 'JavaScript',
    title: 'W3Schools: HTML5 Forms, Attributes & Media Tags Tutorial',
    provider: 'W3Schools',
    type: 'article',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['HTML', 'Forms', 'Input'],
    url: 'https://www.w3schools.com/html/html_forms.asp',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'web-html-practice',
    curriculumKey: 'DEV_HTML',
    language: 'JavaScript',
    title: 'FreeCodeCamp: Responsive Web Design HTML5 Certification',
    provider: 'FreeCodeCamp',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 10,
    tags: ['HTML', 'FreeCodeCamp'],
    url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    free: true,
    order: 3,
    stage: 'practice',
  },

  // ==================== CSS, FLEXBOX, GRID ====================
  {
    id: 'web-css-learn-1',
    curriculumKey: 'DEV_CSS',
    language: 'JavaScript',
    title: 'MDN Web Docs: Learn CSS Layouts, Box Model & Responsive Design',
    provider: 'MDN',
    type: 'article',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['CSS', 'Box Model', 'Responsive'],
    url: 'https://developer.mozilla.org/en-US/docs/Learn/CSS',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-flexbox-learn-1',
    curriculumKey: 'DEV_FLEXBOX',
    language: 'JavaScript',
    title: 'CSS-Tricks: A Complete Guide to Flexbox Layout',
    provider: 'CSS-Tricks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['CSS', 'Flexbox', 'Layout'],
    url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-flexbox-practice',
    curriculumKey: 'DEV_FLEXBOX',
    language: 'JavaScript',
    title: 'Flexbox Froggy: Interactive CSS Flexbox Learning Game',
    provider: 'Flexbox Froggy',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['CSS', 'Flexbox', 'Game'],
    url: 'https://flexboxfroggy.com',
    free: true,
    order: 2,
    stage: 'practice',
  },
  {
    id: 'web-grid-learn-1',
    curriculumKey: 'DEV_GRID',
    language: 'JavaScript',
    title: 'CSS-Tricks: A Complete Guide to CSS Grid',
    provider: 'CSS-Tricks',
    type: 'article',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['CSS', 'Grid', 'Layout'],
    url: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-grid-practice',
    curriculumKey: 'DEV_GRID',
    language: 'JavaScript',
    title: 'Grid Garden: Interactive CSS Grid Learning Game',
    provider: 'Grid Garden',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 2,
    tags: ['CSS', 'Grid', 'Game'],
    url: 'https://cssgridgarden.com',
    free: true,
    order: 2,
    stage: 'practice',
  },

  // ==================== REACT & STATE MANAGEMENT ====================
  {
    id: 'web-react-learn-1',
    curriculumKey: 'DEV_REACT',
    language: 'JavaScript',
    title: 'Official React Documentation & Interactive Tutorials (react.dev)',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 15,
    tags: ['React', 'Hooks', 'JSX', 'State'],
    url: 'https://react.dev',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-react-learn-2',
    curriculumKey: 'DEV_REACT',
    language: 'JavaScript',
    title: 'Namaste React Course by Akshay Saini',
    provider: 'Akshay Saini',
    type: 'video',
    level: 'intermediate',
    estimatedHours: 20,
    tags: ['React', 'Virtual DOM', 'Reconciliation', 'Custom Hooks'],
    url: 'https://www.youtube.com/playlist?list=PLlasXeu85E9c4idTXF4y24l22i08502gq',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'web-react-notes',
    curriculumKey: 'DEV_REACT',
    language: 'JavaScript',
    title: 'React Hooks Complete Deep Dive (useState, useEffect, useMemo, useCallback)',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['React', 'Hooks', 'Notes'],
    url: 'https://react.dev/reference/react/hooks',
    free: true,
    order: 3,
    stage: 'notes',
  },
  {
    id: 'web-react-practice',
    curriculumKey: 'DEV_REACT',
    language: 'JavaScript',
    title: 'React Interview Questions & Practical Architecture Challenges',
    provider: 'GeeksforGeeks',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 6,
    tags: ['React', 'Interview', 'Performance'],
    url: 'https://www.geeksforgeeks.org/reactjs-interview-questions-and-answers/',
    free: true,
    order: 4,
    stage: 'interview',
  },

  // Redux & React Router
  {
    id: 'web-redux-learn-1',
    curriculumKey: 'DEV_REDUX',
    language: 'JavaScript',
    title: 'Redux Toolkit Official Essentials Tutorial & State Management Guide',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 8,
    tags: ['Redux', 'Redux Toolkit', 'Global State'],
    url: 'https://redux-toolkit.js.org/introduction/getting-started',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-router-learn-1',
    curriculumKey: 'DEV_REACT_ROUTER',
    language: 'JavaScript',
    title: 'React Router v6 Official Getting Started Guide & Routing Patterns',
    provider: 'Official Docs',
    type: 'article',
    level: 'intermediate',
    estimatedHours: 5,
    tags: ['React Router', 'Routing', 'SPA'],
    url: 'https://reactrouter.com/en/main/start/tutorial',
    free: true,
    order: 1,
    stage: 'learn',
  },

  // ==================== NEXT.JS & TAILWIND ====================
  {
    id: 'web-nextjs-learn-1',
    curriculumKey: 'DEV_NEXTJS',
    language: 'TypeScript',
    title: 'Vercel Next.js Learn: Complete App Router Course',
    provider: 'Vercel',
    type: 'interactive',
    level: 'intermediate',
    estimatedHours: 12,
    tags: ['Next.js', 'App Router', 'SSR', 'SSG', 'Server Components'],
    url: 'https://nextjs.org/learn',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'web-nextjs-learn-2',
    curriculumKey: 'DEV_NEXTJS',
    language: 'TypeScript',
    title: 'Official Next.js Documentation & Server Actions Guide',
    provider: 'Official Docs',
    type: 'article',
    level: 'advanced',
    estimatedHours: 10,
    tags: ['Next.js', 'Docs'],
    url: 'https://nextjs.org/docs',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'web-tailwind-learn-1',
    curriculumKey: 'DEV_TAILWIND',
    language: 'JavaScript',
    title: 'Official Tailwind CSS Documentation & Core Concepts Guide',
    provider: 'Official Docs',
    type: 'article',
    level: 'beginner',
    estimatedHours: 5,
    tags: ['TailwindCSS', 'CSS', 'Styling'],
    url: 'https://tailwindcss.com/docs',
    free: true,
    order: 1,
    stage: 'learn',
  },
];
