import { LibraryResource } from '../types';

export const toolsResources: LibraryResource[] = [
  // Git & GitHub
  {
    id: 'tool-git-learn-1',
    curriculumKey: 'DEV_GIT',
    language: 'All',
    title: 'Git & GitHub Official Documentation, Interactive Commands & Cheat Sheet',
    provider: 'Official Docs',
    type: 'article',
    level: 'beginner',
    estimatedHours: 6,
    tags: ['Git', 'GitHub', 'Version Control', 'Commits', 'Branches'],
    url: 'https://git-scm.com/doc',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'tool-git-learn-2',
    curriculumKey: 'DEV_GIT',
    language: 'All',
    title: 'FreeCodeCamp: Git and GitHub for Beginners - Crash Course',
    provider: 'FreeCodeCamp',
    type: 'video',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Git', 'GitHub'],
    url: 'https://youtu.be/RGOj5yH7evk',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'tool-git-practice-3',
    curriculumKey: 'DEV_GIT',
    language: 'All',
    title: 'Learn Git Branching: Interactive Visual Git Command Simulator',
    provider: 'LearnGitBranching',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Git', 'Interactive', 'Branching'],
    url: 'https://learngitbranching.js.org',
    free: true,
    order: 3,
    stage: 'practice',
  },

  // VS Code
  {
    id: 'tool-vscode-learn-1',
    curriculumKey: 'DEV_VSCODE',
    language: 'All',
    title: 'Official Visual Studio Code User Guide & Keyboard Shortcuts',
    provider: 'Official Docs',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['VS Code', 'Editor', 'Shortcuts'],
    url: 'https://code.visualstudio.com/docs',
    free: true,
    order: 1,
    stage: 'learn',
  },

  // Linux & Terminal
  {
    id: 'tool-linux-learn-1',
    curriculumKey: 'DEV_LINUX',
    language: 'All',
    title: 'Linux Command Line Basics & Shell Scripting Guide',
    provider: 'FreeCodeCamp',
    type: 'article',
    level: 'beginner',
    estimatedHours: 6,
    tags: ['Linux', 'Terminal', 'Bash', 'CLI'],
    url: 'https://www.freecodecamp.org/news/the-linux-commands-handbook/',
    free: true,
    order: 1,
    stage: 'learn',
  },
  {
    id: 'tool-linux-learn-2',
    curriculumKey: 'DEV_LINUX',
    language: 'All',
    title: 'Linux Journey: Interactive Shell Commands & System Administration',
    provider: 'Linux Journey',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 8,
    tags: ['Linux', 'Bash', 'Permissions'],
    url: 'https://linuxjourney.com',
    free: true,
    order: 2,
    stage: 'learn',
  },

  // Postman
  {
    id: 'tool-postman-learn-1',
    curriculumKey: 'DEV_POSTMAN',
    language: 'All',
    title: 'Official Postman Learning Center: API Testing & Collection Automation',
    provider: 'Official Docs',
    type: 'interactive',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Postman', 'API Testing', 'REST API'],
    url: 'https://learning.postman.com/docs/getting-started/introduction/',
    free: true,
    order: 1,
    stage: 'learn',
  },

  // Netlify & Vercel
  {
    id: 'tool-vercel-learn-1',
    curriculumKey: 'DEV_DEPLOYMENT',
    language: 'All',
    title: 'Vercel Platform Docs: Continuous Deployment, Environment Variables & Serverless Edge Functions',
    provider: 'Vercel',
    type: 'article',
    level: 'beginner',
    estimatedHours: 4,
    tags: ['Vercel', 'Deployment', 'Serverless'],
    url: 'https://vercel.com/docs',
    free: true,
    order: 2,
    stage: 'learn',
  },
  {
    id: 'tool-netlify-learn-1',
    curriculumKey: 'DEV_DEPLOYMENT',
    language: 'All',
    title: 'Netlify Docs: Static Site Hosting & Continuous Git Deployment',
    provider: 'Netlify',
    type: 'article',
    level: 'beginner',
    estimatedHours: 3,
    tags: ['Netlify', 'Deployment', 'Git Integration'],
    url: 'https://docs.netlify.com',
    free: true,
    order: 3,
    stage: 'learn',
  },
];
